// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sevitout/v1/ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	// TriggerAction runs one AI action against a SEV and returns once the
	// provider responds; the result is also stored (ai_outputs) and broadcast
	// over WebSocket as an ai.output event, same as a proactive trigger.
	TriggerAction(ctx context.Context, in *TriggerActionRequest, opts ...grpc.CallOption) (*AIOutputResponse, error)
	// StreamAction runs one AI action and streams its output incrementally —
	// for actions whose provider call may take a while (e.g. DraftPostmortem).
	// The final chunk (done=true) carries the same content that would have
	// been stored had TriggerAction been used instead.
	StreamAction(ctx context.Context, in *TriggerActionRequest, opts ...grpc.CallOption) (AIService_StreamActionClient, error)
	// ListOutputs returns previously generated AI output for a SEV, proactive
	// and user-triggered alike, oldest first.
	ListOutputs(ctx context.Context, in *ListAIOutputsRequest, opts ...grpc.CallOption) (*ListAIOutputsResponse, error)
	// ListPlugins returns the currently enabled AI plugins that
	// TriggerAction/StreamAction can route to. Unlike
	// ConfigService.ListAIPlugins (Admin-only, full record), this is readable
	// by any authenticated user and never includes credentials or handler
	// internals — just enough to populate a "run AI action" menu.
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) TriggerAction(ctx context.Context, in *TriggerActionRequest, opts ...grpc.CallOption) (*AIOutputResponse, error) {
	out := new(AIOutputResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.AIService/TriggerAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) StreamAction(ctx context.Context, in *TriggerActionRequest, opts ...grpc.CallOption) (AIService_StreamActionClient, error) {
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[0], "/sevitout.v1.AIService/StreamAction", opts...)
	if err != nil {
		return nil, err
	}
	x := &aIServiceStreamActionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AIService_StreamActionClient interface {
	Recv() (*AIActionChunk, error)
	grpc.ClientStream
}

type aIServiceStreamActionClient struct {
	grpc.ClientStream
}

func (x *aIServiceStreamActionClient) Recv() (*AIActionChunk, error) {
	m := new(AIActionChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aIServiceClient) ListOutputs(ctx context.Context, in *ListAIOutputsRequest, opts ...grpc.CallOption) (*ListAIOutputsResponse, error) {
	out := new(ListAIOutputsResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.AIService/ListOutputs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.AIService/ListPlugins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility
type AIServiceServer interface {
	// TriggerAction runs one AI action against a SEV and returns once the
	// provider responds; the result is also stored (ai_outputs) and broadcast
	// over WebSocket as an ai.output event, same as a proactive trigger.
	TriggerAction(context.Context, *TriggerActionRequest) (*AIOutputResponse, error)
	// StreamAction runs one AI action and streams its output incrementally —
	// for actions whose provider call may take a while (e.g. DraftPostmortem).
	// The final chunk (done=true) carries the same content that would have
	// been stored had TriggerAction been used instead.
	StreamAction(*TriggerActionRequest, AIService_StreamActionServer) error
	// ListOutputs returns previously generated AI output for a SEV, proactive
	// and user-triggered alike, oldest first.
	ListOutputs(context.Context, *ListAIOutputsRequest) (*ListAIOutputsResponse, error)
	// ListPlugins returns the currently enabled AI plugins that
	// TriggerAction/StreamAction can route to. Unlike
	// ConfigService.ListAIPlugins (Admin-only, full record), this is readable
	// by any authenticated user and never includes credentials or handler
	// internals — just enough to populate a "run AI action" menu.
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIServiceServer struct {
}

func (UnimplementedAIServiceServer) TriggerAction(context.Context, *TriggerActionRequest) (*AIOutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerAction not implemented")
}
func (UnimplementedAIServiceServer) StreamAction(*TriggerActionRequest, AIService_StreamActionServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAction not implemented")
}
func (UnimplementedAIServiceServer) ListOutputs(context.Context, *ListAIOutputsRequest) (*ListAIOutputsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOutputs not implemented")
}
func (UnimplementedAIServiceServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_TriggerAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).TriggerAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.AIService/TriggerAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).TriggerAction(ctx, req.(*TriggerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_StreamAction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TriggerActionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).StreamAction(m, &aIServiceStreamActionServer{stream})
}

type AIService_StreamActionServer interface {
	Send(*AIActionChunk) error
	grpc.ServerStream
}

type aIServiceStreamActionServer struct {
	grpc.ServerStream
}

func (x *aIServiceStreamActionServer) Send(m *AIActionChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _AIService_ListOutputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAIOutputsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ListOutputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.AIService/ListOutputs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ListOutputs(ctx, req.(*ListAIOutputsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.AIService/ListPlugins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sevitout.v1.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerAction",
			Handler:    _AIService_TriggerAction_Handler,
		},
		{
			MethodName: "ListOutputs",
			Handler:    _AIService_ListOutputs_Handler,
		},
		{
			MethodName: "ListPlugins",
			Handler:    _AIService_ListPlugins_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAction",
			Handler:       _AIService_StreamAction_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sevitout/v1/ai.proto",
}
