// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sevitout/v1/chat.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	AddChatEntry(ctx context.Context, in *AddChatEntryRequest, opts ...grpc.CallOption) (*ChatEntryResponse, error)
	ListChatEntries(ctx context.Context, in *ListChatEntriesRequest, opts ...grpc.CallOption) (*ListChatEntriesResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) AddChatEntry(ctx context.Context, in *AddChatEntryRequest, opts ...grpc.CallOption) (*ChatEntryResponse, error) {
	out := new(ChatEntryResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ChatService/AddChatEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListChatEntries(ctx context.Context, in *ListChatEntriesRequest, opts ...grpc.CallOption) (*ListChatEntriesResponse, error) {
	out := new(ListChatEntriesResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ChatService/ListChatEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility
type ChatServiceServer interface {
	AddChatEntry(context.Context, *AddChatEntryRequest) (*ChatEntryResponse, error)
	ListChatEntries(context.Context, *ListChatEntriesRequest) (*ListChatEntriesResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (UnimplementedChatServiceServer) AddChatEntry(context.Context, *AddChatEntryRequest) (*ChatEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddChatEntry not implemented")
}
func (UnimplementedChatServiceServer) ListChatEntries(context.Context, *ListChatEntriesRequest) (*ListChatEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChatEntries not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_AddChatEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddChatEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AddChatEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ChatService/AddChatEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AddChatEntry(ctx, req.(*AddChatEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListChatEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListChatEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ChatService/ListChatEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListChatEntries(ctx, req.(*ListChatEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sevitout.v1.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddChatEntry",
			Handler:    _ChatService_AddChatEntry_Handler,
		},
		{
			MethodName: "ListChatEntries",
			Handler:    _ChatService_ListChatEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sevitout/v1/chat.proto",
}
