// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sevitout/v1/config.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigServiceClient interface {
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	// DeleteService permanently removes a service record. To retire a service
	// while preserving historical SEV references, prefer UpdateService with
	// active=false instead.
	DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListServices is readable by any authenticated user (Viewer+) since
	// services are referenced throughout the system (e.g. picking affected
	// services on a SEV).
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// ListUsers is Admin-only; the directory includes email addresses.
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	UpdateUserRole(ctx context.Context, in *UpdateUserRoleRequest, opts ...grpc.CallOption) (*UserResponse, error)
	DeactivateUser(ctx context.Context, in *DeactivateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	ReactivateUser(ctx context.Context, in *ReactivateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	CreateOnCallRotation(ctx context.Context, in *CreateOnCallRotationRequest, opts ...grpc.CallOption) (*OnCallRotationResponse, error)
	GetOnCallRotation(ctx context.Context, in *GetOnCallRotationRequest, opts ...grpc.CallOption) (*OnCallRotationResponse, error)
	UpdateOnCallRotation(ctx context.Context, in *UpdateOnCallRotationRequest, opts ...grpc.CallOption) (*OnCallRotationResponse, error)
	DeleteOnCallRotation(ctx context.Context, in *DeleteOnCallRotationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListOnCallRotations is readable by any authenticated user (Viewer+) so
	// the UI can show who is currently on-call.
	ListOnCallRotations(ctx context.Context, in *ListOnCallRotationsRequest, opts ...grpc.CallOption) (*ListOnCallRotationsResponse, error)
	// GetIntegrationCatalog returns the fixed, ordered field schema for every
	// integration_type this server recognizes (docs/roadmap.md Phase 9) — a
	// pure translation of internal/integrations/catalog.All with no store
	// access. It's the single source of truth the admin UI renders its
	// sidebar + schema-driven detail form from, and UpsertIntegrationConfig
	// validates incoming requests against the same catalog.
	GetIntegrationCatalog(ctx context.Context, in *GetIntegrationCatalogRequest, opts ...grpc.CallOption) (*GetIntegrationCatalogResponse, error)
	// UpsertIntegrationConfig creates or replaces the settings and credentials
	// for one integration type. Credentials are encrypted (AES-256-GCM) before
	// being written to storage and are never returned by any RPC in this
	// service — only whether credentials are currently configured. The
	// integration_type and every credential/settings key (and, for a select
	// field, its value) are validated against GetIntegrationCatalog's schema
	// before anything is written — see this RPC's handler doc comment.
	UpsertIntegrationConfig(ctx context.Context, in *UpsertIntegrationConfigRequest, opts ...grpc.CallOption) (*IntegrationConfigResponse, error)
	GetIntegrationConfig(ctx context.Context, in *GetIntegrationConfigRequest, opts ...grpc.CallOption) (*IntegrationConfigResponse, error)
	// GetSlackBotCredential returns the decrypted "slack" integration
	// credential pair (bot_token/app_token) — the one deliberate exception to
	// "credentials are never returned by any RPC in this service" above. It
	// exists solely so cmd/slackbot (a separate process that only talks to
	// this API over gRPC, with no direct datastore/encryption-key access) can
	// pick up a datastore-configured Slack token without a restart; see
	// docs/roadmap.md Phase 8. Gated server-side to the specific slackbot
	// service account (SLACKBOT_SERVICE_EMAIL), not merely Admin+ — an
	// unrelated admin session must not be able to pull plaintext Slack tokens
	// through this call. Returns empty fields (not an error) when the "slack"
	// integration has no credentials configured, so callers can fall back to
	// their own static tokens.
	GetSlackBotCredential(ctx context.Context, in *GetSlackBotCredentialRequest, opts ...grpc.CallOption) (*GetSlackBotCredentialResponse, error)
	ListIntegrationConfigs(ctx context.Context, in *ListIntegrationConfigsRequest, opts ...grpc.CallOption) (*ListIntegrationConfigsResponse, error)
	GetRetentionConfig(ctx context.Context, in *GetRetentionConfigRequest, opts ...grpc.CallOption) (*RetentionConfigResponse, error)
	UpdateRetentionConfig(ctx context.Context, in *UpdateRetentionConfigRequest, opts ...grpc.CallOption) (*RetentionConfigResponse, error)
	ListRetentionConfig(ctx context.Context, in *ListRetentionConfigRequest, opts ...grpc.CallOption) (*ListRetentionConfigResponse, error)
	CreateAIPlugin(ctx context.Context, in *CreateAIPluginRequest, opts ...grpc.CallOption) (*AIPluginResponse, error)
	GetAIPlugin(ctx context.Context, in *GetAIPluginRequest, opts ...grpc.CallOption) (*AIPluginResponse, error)
	UpdateAIPlugin(ctx context.Context, in *UpdateAIPluginRequest, opts ...grpc.CallOption) (*AIPluginResponse, error)
	DeleteAIPlugin(ctx context.Context, in *DeleteAIPluginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListAIPlugins(ctx context.Context, in *ListAIPluginsRequest, opts ...grpc.CallOption) (*ListAIPluginsResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/CreateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/GetService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/UpdateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/DeleteService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/ListServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) UpdateUserRole(ctx context.Context, in *UpdateUserRoleRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/UpdateUserRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DeactivateUser(ctx context.Context, in *DeactivateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/DeactivateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ReactivateUser(ctx context.Context, in *ReactivateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/ReactivateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) CreateOnCallRotation(ctx context.Context, in *CreateOnCallRotationRequest, opts ...grpc.CallOption) (*OnCallRotationResponse, error) {
	out := new(OnCallRotationResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/CreateOnCallRotation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetOnCallRotation(ctx context.Context, in *GetOnCallRotationRequest, opts ...grpc.CallOption) (*OnCallRotationResponse, error) {
	out := new(OnCallRotationResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/GetOnCallRotation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) UpdateOnCallRotation(ctx context.Context, in *UpdateOnCallRotationRequest, opts ...grpc.CallOption) (*OnCallRotationResponse, error) {
	out := new(OnCallRotationResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/UpdateOnCallRotation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DeleteOnCallRotation(ctx context.Context, in *DeleteOnCallRotationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/DeleteOnCallRotation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListOnCallRotations(ctx context.Context, in *ListOnCallRotationsRequest, opts ...grpc.CallOption) (*ListOnCallRotationsResponse, error) {
	out := new(ListOnCallRotationsResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/ListOnCallRotations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetIntegrationCatalog(ctx context.Context, in *GetIntegrationCatalogRequest, opts ...grpc.CallOption) (*GetIntegrationCatalogResponse, error) {
	out := new(GetIntegrationCatalogResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/GetIntegrationCatalog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) UpsertIntegrationConfig(ctx context.Context, in *UpsertIntegrationConfigRequest, opts ...grpc.CallOption) (*IntegrationConfigResponse, error) {
	out := new(IntegrationConfigResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/UpsertIntegrationConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetIntegrationConfig(ctx context.Context, in *GetIntegrationConfigRequest, opts ...grpc.CallOption) (*IntegrationConfigResponse, error) {
	out := new(IntegrationConfigResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/GetIntegrationConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetSlackBotCredential(ctx context.Context, in *GetSlackBotCredentialRequest, opts ...grpc.CallOption) (*GetSlackBotCredentialResponse, error) {
	out := new(GetSlackBotCredentialResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/GetSlackBotCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListIntegrationConfigs(ctx context.Context, in *ListIntegrationConfigsRequest, opts ...grpc.CallOption) (*ListIntegrationConfigsResponse, error) {
	out := new(ListIntegrationConfigsResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/ListIntegrationConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetRetentionConfig(ctx context.Context, in *GetRetentionConfigRequest, opts ...grpc.CallOption) (*RetentionConfigResponse, error) {
	out := new(RetentionConfigResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/GetRetentionConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) UpdateRetentionConfig(ctx context.Context, in *UpdateRetentionConfigRequest, opts ...grpc.CallOption) (*RetentionConfigResponse, error) {
	out := new(RetentionConfigResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/UpdateRetentionConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListRetentionConfig(ctx context.Context, in *ListRetentionConfigRequest, opts ...grpc.CallOption) (*ListRetentionConfigResponse, error) {
	out := new(ListRetentionConfigResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/ListRetentionConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) CreateAIPlugin(ctx context.Context, in *CreateAIPluginRequest, opts ...grpc.CallOption) (*AIPluginResponse, error) {
	out := new(AIPluginResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/CreateAIPlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetAIPlugin(ctx context.Context, in *GetAIPluginRequest, opts ...grpc.CallOption) (*AIPluginResponse, error) {
	out := new(AIPluginResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/GetAIPlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) UpdateAIPlugin(ctx context.Context, in *UpdateAIPluginRequest, opts ...grpc.CallOption) (*AIPluginResponse, error) {
	out := new(AIPluginResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/UpdateAIPlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DeleteAIPlugin(ctx context.Context, in *DeleteAIPluginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/DeleteAIPlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListAIPlugins(ctx context.Context, in *ListAIPluginsRequest, opts ...grpc.CallOption) (*ListAIPluginsResponse, error) {
	out := new(ListAIPluginsResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ConfigService/ListAIPlugins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility
type ConfigServiceServer interface {
	CreateService(context.Context, *CreateServiceRequest) (*ServiceResponse, error)
	GetService(context.Context, *GetServiceRequest) (*ServiceResponse, error)
	UpdateService(context.Context, *UpdateServiceRequest) (*ServiceResponse, error)
	// DeleteService permanently removes a service record. To retire a service
	// while preserving historical SEV references, prefer UpdateService with
	// active=false instead.
	DeleteService(context.Context, *DeleteServiceRequest) (*emptypb.Empty, error)
	// ListServices is readable by any authenticated user (Viewer+) since
	// services are referenced throughout the system (e.g. picking affected
	// services on a SEV).
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// ListUsers is Admin-only; the directory includes email addresses.
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	UpdateUserRole(context.Context, *UpdateUserRoleRequest) (*UserResponse, error)
	DeactivateUser(context.Context, *DeactivateUserRequest) (*UserResponse, error)
	ReactivateUser(context.Context, *ReactivateUserRequest) (*UserResponse, error)
	CreateOnCallRotation(context.Context, *CreateOnCallRotationRequest) (*OnCallRotationResponse, error)
	GetOnCallRotation(context.Context, *GetOnCallRotationRequest) (*OnCallRotationResponse, error)
	UpdateOnCallRotation(context.Context, *UpdateOnCallRotationRequest) (*OnCallRotationResponse, error)
	DeleteOnCallRotation(context.Context, *DeleteOnCallRotationRequest) (*emptypb.Empty, error)
	// ListOnCallRotations is readable by any authenticated user (Viewer+) so
	// the UI can show who is currently on-call.
	ListOnCallRotations(context.Context, *ListOnCallRotationsRequest) (*ListOnCallRotationsResponse, error)
	// GetIntegrationCatalog returns the fixed, ordered field schema for every
	// integration_type this server recognizes (docs/roadmap.md Phase 9) — a
	// pure translation of internal/integrations/catalog.All with no store
	// access. It's the single source of truth the admin UI renders its
	// sidebar + schema-driven detail form from, and UpsertIntegrationConfig
	// validates incoming requests against the same catalog.
	GetIntegrationCatalog(context.Context, *GetIntegrationCatalogRequest) (*GetIntegrationCatalogResponse, error)
	// UpsertIntegrationConfig creates or replaces the settings and credentials
	// for one integration type. Credentials are encrypted (AES-256-GCM) before
	// being written to storage and are never returned by any RPC in this
	// service — only whether credentials are currently configured. The
	// integration_type and every credential/settings key (and, for a select
	// field, its value) are validated against GetIntegrationCatalog's schema
	// before anything is written — see this RPC's handler doc comment.
	UpsertIntegrationConfig(context.Context, *UpsertIntegrationConfigRequest) (*IntegrationConfigResponse, error)
	GetIntegrationConfig(context.Context, *GetIntegrationConfigRequest) (*IntegrationConfigResponse, error)
	// GetSlackBotCredential returns the decrypted "slack" integration
	// credential pair (bot_token/app_token) — the one deliberate exception to
	// "credentials are never returned by any RPC in this service" above. It
	// exists solely so cmd/slackbot (a separate process that only talks to
	// this API over gRPC, with no direct datastore/encryption-key access) can
	// pick up a datastore-configured Slack token without a restart; see
	// docs/roadmap.md Phase 8. Gated server-side to the specific slackbot
	// service account (SLACKBOT_SERVICE_EMAIL), not merely Admin+ — an
	// unrelated admin session must not be able to pull plaintext Slack tokens
	// through this call. Returns empty fields (not an error) when the "slack"
	// integration has no credentials configured, so callers can fall back to
	// their own static tokens.
	GetSlackBotCredential(context.Context, *GetSlackBotCredentialRequest) (*GetSlackBotCredentialResponse, error)
	ListIntegrationConfigs(context.Context, *ListIntegrationConfigsRequest) (*ListIntegrationConfigsResponse, error)
	GetRetentionConfig(context.Context, *GetRetentionConfigRequest) (*RetentionConfigResponse, error)
	UpdateRetentionConfig(context.Context, *UpdateRetentionConfigRequest) (*RetentionConfigResponse, error)
	ListRetentionConfig(context.Context, *ListRetentionConfigRequest) (*ListRetentionConfigResponse, error)
	CreateAIPlugin(context.Context, *CreateAIPluginRequest) (*AIPluginResponse, error)
	GetAIPlugin(context.Context, *GetAIPluginRequest) (*AIPluginResponse, error)
	UpdateAIPlugin(context.Context, *UpdateAIPluginRequest) (*AIPluginResponse, error)
	DeleteAIPlugin(context.Context, *DeleteAIPluginRequest) (*emptypb.Empty, error)
	ListAIPlugins(context.Context, *ListAIPluginsRequest) (*ListAIPluginsResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConfigServiceServer struct {
}

func (UnimplementedConfigServiceServer) CreateService(context.Context, *CreateServiceRequest) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedConfigServiceServer) GetService(context.Context, *GetServiceRequest) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedConfigServiceServer) UpdateService(context.Context, *UpdateServiceRequest) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedConfigServiceServer) DeleteService(context.Context, *DeleteServiceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedConfigServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedConfigServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedConfigServiceServer) UpdateUserRole(context.Context, *UpdateUserRoleRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserRole not implemented")
}
func (UnimplementedConfigServiceServer) DeactivateUser(context.Context, *DeactivateUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateUser not implemented")
}
func (UnimplementedConfigServiceServer) ReactivateUser(context.Context, *ReactivateUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReactivateUser not implemented")
}
func (UnimplementedConfigServiceServer) CreateOnCallRotation(context.Context, *CreateOnCallRotationRequest) (*OnCallRotationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOnCallRotation not implemented")
}
func (UnimplementedConfigServiceServer) GetOnCallRotation(context.Context, *GetOnCallRotationRequest) (*OnCallRotationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnCallRotation not implemented")
}
func (UnimplementedConfigServiceServer) UpdateOnCallRotation(context.Context, *UpdateOnCallRotationRequest) (*OnCallRotationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOnCallRotation not implemented")
}
func (UnimplementedConfigServiceServer) DeleteOnCallRotation(context.Context, *DeleteOnCallRotationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOnCallRotation not implemented")
}
func (UnimplementedConfigServiceServer) ListOnCallRotations(context.Context, *ListOnCallRotationsRequest) (*ListOnCallRotationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOnCallRotations not implemented")
}
func (UnimplementedConfigServiceServer) GetIntegrationCatalog(context.Context, *GetIntegrationCatalogRequest) (*GetIntegrationCatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegrationCatalog not implemented")
}
func (UnimplementedConfigServiceServer) UpsertIntegrationConfig(context.Context, *UpsertIntegrationConfigRequest) (*IntegrationConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertIntegrationConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetIntegrationConfig(context.Context, *GetIntegrationConfigRequest) (*IntegrationConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegrationConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetSlackBotCredential(context.Context, *GetSlackBotCredentialRequest) (*GetSlackBotCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlackBotCredential not implemented")
}
func (UnimplementedConfigServiceServer) ListIntegrationConfigs(context.Context, *ListIntegrationConfigsRequest) (*ListIntegrationConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIntegrationConfigs not implemented")
}
func (UnimplementedConfigServiceServer) GetRetentionConfig(context.Context, *GetRetentionConfigRequest) (*RetentionConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRetentionConfig not implemented")
}
func (UnimplementedConfigServiceServer) UpdateRetentionConfig(context.Context, *UpdateRetentionConfigRequest) (*RetentionConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRetentionConfig not implemented")
}
func (UnimplementedConfigServiceServer) ListRetentionConfig(context.Context, *ListRetentionConfigRequest) (*ListRetentionConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRetentionConfig not implemented")
}
func (UnimplementedConfigServiceServer) CreateAIPlugin(context.Context, *CreateAIPluginRequest) (*AIPluginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAIPlugin not implemented")
}
func (UnimplementedConfigServiceServer) GetAIPlugin(context.Context, *GetAIPluginRequest) (*AIPluginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAIPlugin not implemented")
}
func (UnimplementedConfigServiceServer) UpdateAIPlugin(context.Context, *UpdateAIPluginRequest) (*AIPluginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAIPlugin not implemented")
}
func (UnimplementedConfigServiceServer) DeleteAIPlugin(context.Context, *DeleteAIPluginRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAIPlugin not implemented")
}
func (UnimplementedConfigServiceServer) ListAIPlugins(context.Context, *ListAIPluginsRequest) (*ListAIPluginsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAIPlugins not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/CreateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/GetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/UpdateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).UpdateService(ctx, req.(*UpdateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/DeleteService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteService(ctx, req.(*DeleteServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/ListServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_UpdateUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).UpdateUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/UpdateUserRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).UpdateUserRole(ctx, req.(*UpdateUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeactivateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeactivateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/DeactivateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeactivateUser(ctx, req.(*DeactivateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ReactivateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactivateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ReactivateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/ReactivateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ReactivateUser(ctx, req.(*ReactivateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_CreateOnCallRotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOnCallRotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).CreateOnCallRotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/CreateOnCallRotation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).CreateOnCallRotation(ctx, req.(*CreateOnCallRotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetOnCallRotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnCallRotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetOnCallRotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/GetOnCallRotation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetOnCallRotation(ctx, req.(*GetOnCallRotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_UpdateOnCallRotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOnCallRotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).UpdateOnCallRotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/UpdateOnCallRotation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).UpdateOnCallRotation(ctx, req.(*UpdateOnCallRotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteOnCallRotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOnCallRotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteOnCallRotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/DeleteOnCallRotation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteOnCallRotation(ctx, req.(*DeleteOnCallRotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListOnCallRotations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOnCallRotationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListOnCallRotations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/ListOnCallRotations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListOnCallRotations(ctx, req.(*ListOnCallRotationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetIntegrationCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntegrationCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetIntegrationCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/GetIntegrationCatalog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetIntegrationCatalog(ctx, req.(*GetIntegrationCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_UpsertIntegrationConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertIntegrationConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).UpsertIntegrationConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/UpsertIntegrationConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).UpsertIntegrationConfig(ctx, req.(*UpsertIntegrationConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetIntegrationConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntegrationConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetIntegrationConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/GetIntegrationConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetIntegrationConfig(ctx, req.(*GetIntegrationConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetSlackBotCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSlackBotCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetSlackBotCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/GetSlackBotCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetSlackBotCredential(ctx, req.(*GetSlackBotCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListIntegrationConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIntegrationConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListIntegrationConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/ListIntegrationConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListIntegrationConfigs(ctx, req.(*ListIntegrationConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetRetentionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRetentionConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetRetentionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/GetRetentionConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetRetentionConfig(ctx, req.(*GetRetentionConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_UpdateRetentionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRetentionConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).UpdateRetentionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/UpdateRetentionConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).UpdateRetentionConfig(ctx, req.(*UpdateRetentionConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListRetentionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRetentionConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListRetentionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/ListRetentionConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListRetentionConfig(ctx, req.(*ListRetentionConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_CreateAIPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAIPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).CreateAIPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/CreateAIPlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).CreateAIPlugin(ctx, req.(*CreateAIPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetAIPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAIPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetAIPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/GetAIPlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetAIPlugin(ctx, req.(*GetAIPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_UpdateAIPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAIPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).UpdateAIPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/UpdateAIPlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).UpdateAIPlugin(ctx, req.(*UpdateAIPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteAIPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAIPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteAIPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/DeleteAIPlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteAIPlugin(ctx, req.(*DeleteAIPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListAIPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAIPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListAIPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ConfigService/ListAIPlugins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListAIPlugins(ctx, req.(*ListAIPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sevitout.v1.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateService",
			Handler:    _ConfigService_CreateService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _ConfigService_GetService_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _ConfigService_UpdateService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _ConfigService_DeleteService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ConfigService_ListServices_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _ConfigService_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUserRole",
			Handler:    _ConfigService_UpdateUserRole_Handler,
		},
		{
			MethodName: "DeactivateUser",
			Handler:    _ConfigService_DeactivateUser_Handler,
		},
		{
			MethodName: "ReactivateUser",
			Handler:    _ConfigService_ReactivateUser_Handler,
		},
		{
			MethodName: "CreateOnCallRotation",
			Handler:    _ConfigService_CreateOnCallRotation_Handler,
		},
		{
			MethodName: "GetOnCallRotation",
			Handler:    _ConfigService_GetOnCallRotation_Handler,
		},
		{
			MethodName: "UpdateOnCallRotation",
			Handler:    _ConfigService_UpdateOnCallRotation_Handler,
		},
		{
			MethodName: "DeleteOnCallRotation",
			Handler:    _ConfigService_DeleteOnCallRotation_Handler,
		},
		{
			MethodName: "ListOnCallRotations",
			Handler:    _ConfigService_ListOnCallRotations_Handler,
		},
		{
			MethodName: "GetIntegrationCatalog",
			Handler:    _ConfigService_GetIntegrationCatalog_Handler,
		},
		{
			MethodName: "UpsertIntegrationConfig",
			Handler:    _ConfigService_UpsertIntegrationConfig_Handler,
		},
		{
			MethodName: "GetIntegrationConfig",
			Handler:    _ConfigService_GetIntegrationConfig_Handler,
		},
		{
			MethodName: "GetSlackBotCredential",
			Handler:    _ConfigService_GetSlackBotCredential_Handler,
		},
		{
			MethodName: "ListIntegrationConfigs",
			Handler:    _ConfigService_ListIntegrationConfigs_Handler,
		},
		{
			MethodName: "GetRetentionConfig",
			Handler:    _ConfigService_GetRetentionConfig_Handler,
		},
		{
			MethodName: "UpdateRetentionConfig",
			Handler:    _ConfigService_UpdateRetentionConfig_Handler,
		},
		{
			MethodName: "ListRetentionConfig",
			Handler:    _ConfigService_ListRetentionConfig_Handler,
		},
		{
			MethodName: "CreateAIPlugin",
			Handler:    _ConfigService_CreateAIPlugin_Handler,
		},
		{
			MethodName: "GetAIPlugin",
			Handler:    _ConfigService_GetAIPlugin_Handler,
		},
		{
			MethodName: "UpdateAIPlugin",
			Handler:    _ConfigService_UpdateAIPlugin_Handler,
		},
		{
			MethodName: "DeleteAIPlugin",
			Handler:    _ConfigService_DeleteAIPlugin_Handler,
		},
		{
			MethodName: "ListAIPlugins",
			Handler:    _ConfigService_ListAIPlugins_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sevitout/v1/config.proto",
}
