// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sevitout/v1/postmortem.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostmortemServiceClient is the client API for PostmortemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostmortemServiceClient interface {
	GetPostmortem(ctx context.Context, in *GetPostmortemRequest, opts ...grpc.CallOption) (*PostmortemResponse, error)
	UpdatePostmortem(ctx context.Context, in *UpdatePostmortemRequest, opts ...grpc.CallOption) (*PostmortemResponse, error)
	TransitionPostmortemStatus(ctx context.Context, in *TransitionPostmortemStatusRequest, opts ...grpc.CallOption) (*PostmortemResponse, error)
	UnlockSEV(ctx context.Context, in *UnlockSEVRequest, opts ...grpc.CallOption) (*UnlockSEVResponse, error)
}

type postmortemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostmortemServiceClient(cc grpc.ClientConnInterface) PostmortemServiceClient {
	return &postmortemServiceClient{cc}
}

func (c *postmortemServiceClient) GetPostmortem(ctx context.Context, in *GetPostmortemRequest, opts ...grpc.CallOption) (*PostmortemResponse, error) {
	out := new(PostmortemResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.PostmortemService/GetPostmortem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postmortemServiceClient) UpdatePostmortem(ctx context.Context, in *UpdatePostmortemRequest, opts ...grpc.CallOption) (*PostmortemResponse, error) {
	out := new(PostmortemResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.PostmortemService/UpdatePostmortem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postmortemServiceClient) TransitionPostmortemStatus(ctx context.Context, in *TransitionPostmortemStatusRequest, opts ...grpc.CallOption) (*PostmortemResponse, error) {
	out := new(PostmortemResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.PostmortemService/TransitionPostmortemStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postmortemServiceClient) UnlockSEV(ctx context.Context, in *UnlockSEVRequest, opts ...grpc.CallOption) (*UnlockSEVResponse, error) {
	out := new(UnlockSEVResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.PostmortemService/UnlockSEV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostmortemServiceServer is the server API for PostmortemService service.
// All implementations must embed UnimplementedPostmortemServiceServer
// for forward compatibility
type PostmortemServiceServer interface {
	GetPostmortem(context.Context, *GetPostmortemRequest) (*PostmortemResponse, error)
	UpdatePostmortem(context.Context, *UpdatePostmortemRequest) (*PostmortemResponse, error)
	TransitionPostmortemStatus(context.Context, *TransitionPostmortemStatusRequest) (*PostmortemResponse, error)
	UnlockSEV(context.Context, *UnlockSEVRequest) (*UnlockSEVResponse, error)
	mustEmbedUnimplementedPostmortemServiceServer()
}

// UnimplementedPostmortemServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPostmortemServiceServer struct {
}

func (UnimplementedPostmortemServiceServer) GetPostmortem(context.Context, *GetPostmortemRequest) (*PostmortemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostmortem not implemented")
}
func (UnimplementedPostmortemServiceServer) UpdatePostmortem(context.Context, *UpdatePostmortemRequest) (*PostmortemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePostmortem not implemented")
}
func (UnimplementedPostmortemServiceServer) TransitionPostmortemStatus(context.Context, *TransitionPostmortemStatusRequest) (*PostmortemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionPostmortemStatus not implemented")
}
func (UnimplementedPostmortemServiceServer) UnlockSEV(context.Context, *UnlockSEVRequest) (*UnlockSEVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockSEV not implemented")
}
func (UnimplementedPostmortemServiceServer) mustEmbedUnimplementedPostmortemServiceServer() {}

// UnsafePostmortemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostmortemServiceServer will
// result in compilation errors.
type UnsafePostmortemServiceServer interface {
	mustEmbedUnimplementedPostmortemServiceServer()
}

func RegisterPostmortemServiceServer(s grpc.ServiceRegistrar, srv PostmortemServiceServer) {
	s.RegisterService(&PostmortemService_ServiceDesc, srv)
}

func _PostmortemService_GetPostmortem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostmortemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostmortemServiceServer).GetPostmortem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.PostmortemService/GetPostmortem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostmortemServiceServer).GetPostmortem(ctx, req.(*GetPostmortemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostmortemService_UpdatePostmortem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostmortemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostmortemServiceServer).UpdatePostmortem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.PostmortemService/UpdatePostmortem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostmortemServiceServer).UpdatePostmortem(ctx, req.(*UpdatePostmortemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostmortemService_TransitionPostmortemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionPostmortemStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostmortemServiceServer).TransitionPostmortemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.PostmortemService/TransitionPostmortemStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostmortemServiceServer).TransitionPostmortemStatus(ctx, req.(*TransitionPostmortemStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostmortemService_UnlockSEV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockSEVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostmortemServiceServer).UnlockSEV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.PostmortemService/UnlockSEV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostmortemServiceServer).UnlockSEV(ctx, req.(*UnlockSEVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostmortemService_ServiceDesc is the grpc.ServiceDesc for PostmortemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostmortemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sevitout.v1.PostmortemService",
	HandlerType: (*PostmortemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostmortem",
			Handler:    _PostmortemService_GetPostmortem_Handler,
		},
		{
			MethodName: "UpdatePostmortem",
			Handler:    _PostmortemService_UpdatePostmortem_Handler,
		},
		{
			MethodName: "TransitionPostmortemStatus",
			Handler:    _PostmortemService_TransitionPostmortemStatus_Handler,
		},
		{
			MethodName: "UnlockSEV",
			Handler:    _PostmortemService_UnlockSEV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sevitout/v1/postmortem.proto",
}
