// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sevitout/v1/report.proto

package pb

import (
	context "context"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportServiceClient interface {
	GetDashboardMetrics(ctx context.Context, in *GetDashboardMetricsRequest, opts ...grpc.CallOption) (*DashboardMetricsResponse, error)
	// GetSEVTrends surfaces recurring failure patterns: SEVs sharing the same
	// affected service and root cause category (§17's "recurring incident
	// flag").
	GetSEVTrends(ctx context.Context, in *GetSEVTrendsRequest, opts ...grpc.CallOption) (*SEVTrendsResponse, error)
	// ExportSEVs returns a filtered SEV list as CSV. The response is raw
	// text/csv bytes (google.api.HttpBody), not JSON — cmd/server/main.go
	// wraps the gateway's marshaler in runtime.HTTPBodyMarshaler, which
	// detects this response type and writes GetData() as the HTTP body with
	// GetContentType() as Content-Type instead of JSON-encoding it.
	ExportSEVs(ctx context.Context, in *ExportSEVsRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
	// GetServiceMetrics aggregates SEVs into per-(service, severity level)
	// rollups over a trailing window: SEV count, average MTTD/MTTM/MTTR, and
	// an SLA compliance breakdown (docs/roadmap.md Phase 13 — the aggregate
	// counterpart to Phase 12's per-SEV live sla_status on SEVResponse).
	GetServiceMetrics(ctx context.Context, in *GetServiceMetricsRequest, opts ...grpc.CallOption) (*ServiceMetricsResponse, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) GetDashboardMetrics(ctx context.Context, in *GetDashboardMetricsRequest, opts ...grpc.CallOption) (*DashboardMetricsResponse, error) {
	out := new(DashboardMetricsResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ReportService/GetDashboardMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetSEVTrends(ctx context.Context, in *GetSEVTrendsRequest, opts ...grpc.CallOption) (*SEVTrendsResponse, error) {
	out := new(SEVTrendsResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ReportService/GetSEVTrends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) ExportSEVs(ctx context.Context, in *ExportSEVsRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ReportService/ExportSEVs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetServiceMetrics(ctx context.Context, in *GetServiceMetricsRequest, opts ...grpc.CallOption) (*ServiceMetricsResponse, error) {
	out := new(ServiceMetricsResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.ReportService/GetServiceMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
// All implementations must embed UnimplementedReportServiceServer
// for forward compatibility
type ReportServiceServer interface {
	GetDashboardMetrics(context.Context, *GetDashboardMetricsRequest) (*DashboardMetricsResponse, error)
	// GetSEVTrends surfaces recurring failure patterns: SEVs sharing the same
	// affected service and root cause category (§17's "recurring incident
	// flag").
	GetSEVTrends(context.Context, *GetSEVTrendsRequest) (*SEVTrendsResponse, error)
	// ExportSEVs returns a filtered SEV list as CSV. The response is raw
	// text/csv bytes (google.api.HttpBody), not JSON — cmd/server/main.go
	// wraps the gateway's marshaler in runtime.HTTPBodyMarshaler, which
	// detects this response type and writes GetData() as the HTTP body with
	// GetContentType() as Content-Type instead of JSON-encoding it.
	ExportSEVs(context.Context, *ExportSEVsRequest) (*httpbody.HttpBody, error)
	// GetServiceMetrics aggregates SEVs into per-(service, severity level)
	// rollups over a trailing window: SEV count, average MTTD/MTTM/MTTR, and
	// an SLA compliance breakdown (docs/roadmap.md Phase 13 — the aggregate
	// counterpart to Phase 12's per-SEV live sla_status on SEVResponse).
	GetServiceMetrics(context.Context, *GetServiceMetricsRequest) (*ServiceMetricsResponse, error)
	mustEmbedUnimplementedReportServiceServer()
}

// UnimplementedReportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReportServiceServer struct {
}

func (UnimplementedReportServiceServer) GetDashboardMetrics(context.Context, *GetDashboardMetricsRequest) (*DashboardMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardMetrics not implemented")
}
func (UnimplementedReportServiceServer) GetSEVTrends(context.Context, *GetSEVTrendsRequest) (*SEVTrendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSEVTrends not implemented")
}
func (UnimplementedReportServiceServer) ExportSEVs(context.Context, *ExportSEVsRequest) (*httpbody.HttpBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportSEVs not implemented")
}
func (UnimplementedReportServiceServer) GetServiceMetrics(context.Context, *GetServiceMetricsRequest) (*ServiceMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceMetrics not implemented")
}
func (UnimplementedReportServiceServer) mustEmbedUnimplementedReportServiceServer() {}

// UnsafeReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServiceServer will
// result in compilation errors.
type UnsafeReportServiceServer interface {
	mustEmbedUnimplementedReportServiceServer()
}

func RegisterReportServiceServer(s grpc.ServiceRegistrar, srv ReportServiceServer) {
	s.RegisterService(&ReportService_ServiceDesc, srv)
}

func _ReportService_GetDashboardMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetDashboardMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ReportService/GetDashboardMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetDashboardMetrics(ctx, req.(*GetDashboardMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetSEVTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSEVTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetSEVTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ReportService/GetSEVTrends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetSEVTrends(ctx, req.(*GetSEVTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_ExportSEVs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSEVsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).ExportSEVs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ReportService/ExportSEVs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).ExportSEVs(ctx, req.(*ExportSEVsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetServiceMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetServiceMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.ReportService/GetServiceMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetServiceMetrics(ctx, req.(*GetServiceMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportService_ServiceDesc is the grpc.ServiceDesc for ReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sevitout.v1.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboardMetrics",
			Handler:    _ReportService_GetDashboardMetrics_Handler,
		},
		{
			MethodName: "GetSEVTrends",
			Handler:    _ReportService_GetSEVTrends_Handler,
		},
		{
			MethodName: "ExportSEVs",
			Handler:    _ReportService_ExportSEVs_Handler,
		},
		{
			MethodName: "GetServiceMetrics",
			Handler:    _ReportService_GetServiceMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sevitout/v1/report.proto",
}
