// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sevitout/v1/role.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RoleServiceClient is the client API for RoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoleServiceClient interface {
	// AssignRole, in addition to recording the assignment, best-effort invites
	// the role holder into the SEV's incident Slack channel when one is
	// already recorded (SEV.slack_channel_id) — every assigned role gets
	// added automatically, not just those present at channel-creation time
	// (docs/roadmap.md Phase 11 follow-up). A Slack-side failure here never
	// fails the assignment itself; InviteRoleToSlack below remains available
	// to retry or to invite a role assigned before the channel existed.
	AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*SEVRoleResponse, error)
	RemoveRole(ctx context.Context, in *RemoveRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
	// InviteRoleToSlack invites the person holding one role assignment into
	// the SEV's already-created incident Slack channel (docs/roadmap.md Phase
	// 10e) — a manual "add to chat" action for a role assigned after the
	// channel was created (auto-invite at channel-creation time only covers
	// roles that existed at that moment). Fails FailedPrecondition when the
	// SEV has no Slack channel recorded, or when the role holder has no
	// resolvable Slack identity.
	InviteRoleToSlack(ctx context.Context, in *InviteRoleToSlackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// JoinSlackChannel is a self-service "add me" action (docs/roadmap.md
	// Phase 11c) — unlike InviteRoleToSlack, it invites the *caller*, not a
	// named role holder, so it needs no role_id and no IC/Responder floor:
	// any Viewer with real (non visibility-restricted) access to the SEV may
	// call it. Resolution order is the caller's own identity: stored
	// SlackUserID, then LookupUserIDByEmail against the caller's own email.
	// FailedPrecondition when the SEV has no Slack channel recorded or the
	// caller has no resolvable Slack identity; PermissionDenied when the
	// caller lacks full access to a Sensitive SEV — see the handler's doc
	// comment for why that check is explicit here and wasn't part of Phase
	// 10e's InviteRoleToSlack.
	JoinSlackChannel(ctx context.Context, in *JoinSlackChannelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type roleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleServiceClient(cc grpc.ClientConnInterface) RoleServiceClient {
	return &roleServiceClient{cc}
}

func (c *roleServiceClient) AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*SEVRoleResponse, error) {
	out := new(SEVRoleResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.RoleService/AssignRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) RemoveRole(ctx context.Context, in *RemoveRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/sevitout.v1.RoleService/RemoveRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	out := new(ListRolesResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.RoleService/ListRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) InviteRoleToSlack(ctx context.Context, in *InviteRoleToSlackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/sevitout.v1.RoleService/InviteRoleToSlack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) JoinSlackChannel(ctx context.Context, in *JoinSlackChannelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/sevitout.v1.RoleService/JoinSlackChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleServiceServer is the server API for RoleService service.
// All implementations must embed UnimplementedRoleServiceServer
// for forward compatibility
type RoleServiceServer interface {
	// AssignRole, in addition to recording the assignment, best-effort invites
	// the role holder into the SEV's incident Slack channel when one is
	// already recorded (SEV.slack_channel_id) — every assigned role gets
	// added automatically, not just those present at channel-creation time
	// (docs/roadmap.md Phase 11 follow-up). A Slack-side failure here never
	// fails the assignment itself; InviteRoleToSlack below remains available
	// to retry or to invite a role assigned before the channel existed.
	AssignRole(context.Context, *AssignRoleRequest) (*SEVRoleResponse, error)
	RemoveRole(context.Context, *RemoveRoleRequest) (*emptypb.Empty, error)
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error)
	// InviteRoleToSlack invites the person holding one role assignment into
	// the SEV's already-created incident Slack channel (docs/roadmap.md Phase
	// 10e) — a manual "add to chat" action for a role assigned after the
	// channel was created (auto-invite at channel-creation time only covers
	// roles that existed at that moment). Fails FailedPrecondition when the
	// SEV has no Slack channel recorded, or when the role holder has no
	// resolvable Slack identity.
	InviteRoleToSlack(context.Context, *InviteRoleToSlackRequest) (*emptypb.Empty, error)
	// JoinSlackChannel is a self-service "add me" action (docs/roadmap.md
	// Phase 11c) — unlike InviteRoleToSlack, it invites the *caller*, not a
	// named role holder, so it needs no role_id and no IC/Responder floor:
	// any Viewer with real (non visibility-restricted) access to the SEV may
	// call it. Resolution order is the caller's own identity: stored
	// SlackUserID, then LookupUserIDByEmail against the caller's own email.
	// FailedPrecondition when the SEV has no Slack channel recorded or the
	// caller has no resolvable Slack identity; PermissionDenied when the
	// caller lacks full access to a Sensitive SEV — see the handler's doc
	// comment for why that check is explicit here and wasn't part of Phase
	// 10e's InviteRoleToSlack.
	JoinSlackChannel(context.Context, *JoinSlackChannelRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRoleServiceServer()
}

// UnimplementedRoleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRoleServiceServer struct {
}

func (UnimplementedRoleServiceServer) AssignRole(context.Context, *AssignRoleRequest) (*SEVRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignRole not implemented")
}
func (UnimplementedRoleServiceServer) RemoveRole(context.Context, *RemoveRoleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRole not implemented")
}
func (UnimplementedRoleServiceServer) ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoles not implemented")
}
func (UnimplementedRoleServiceServer) InviteRoleToSlack(context.Context, *InviteRoleToSlackRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteRoleToSlack not implemented")
}
func (UnimplementedRoleServiceServer) JoinSlackChannel(context.Context, *JoinSlackChannelRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinSlackChannel not implemented")
}
func (UnimplementedRoleServiceServer) mustEmbedUnimplementedRoleServiceServer() {}

// UnsafeRoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleServiceServer will
// result in compilation errors.
type UnsafeRoleServiceServer interface {
	mustEmbedUnimplementedRoleServiceServer()
}

func RegisterRoleServiceServer(s grpc.ServiceRegistrar, srv RoleServiceServer) {
	s.RegisterService(&RoleService_ServiceDesc, srv)
}

func _RoleService_AssignRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).AssignRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.RoleService/AssignRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).AssignRole(ctx, req.(*AssignRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_RemoveRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).RemoveRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.RoleService/RemoveRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).RemoveRole(ctx, req.(*RemoveRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.RoleService/ListRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).ListRoles(ctx, req.(*ListRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_InviteRoleToSlack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteRoleToSlackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).InviteRoleToSlack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.RoleService/InviteRoleToSlack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).InviteRoleToSlack(ctx, req.(*InviteRoleToSlackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_JoinSlackChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinSlackChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).JoinSlackChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.RoleService/JoinSlackChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).JoinSlackChannel(ctx, req.(*JoinSlackChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleService_ServiceDesc is the grpc.ServiceDesc for RoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sevitout.v1.RoleService",
	HandlerType: (*RoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignRole",
			Handler:    _RoleService_AssignRole_Handler,
		},
		{
			MethodName: "RemoveRole",
			Handler:    _RoleService_RemoveRole_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _RoleService_ListRoles_Handler,
		},
		{
			MethodName: "InviteRoleToSlack",
			Handler:    _RoleService_InviteRoleToSlack_Handler,
		},
		{
			MethodName: "JoinSlackChannel",
			Handler:    _RoleService_JoinSlackChannel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sevitout/v1/role.proto",
}
