// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sevitout/v1/sev.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SEVServiceClient is the client API for SEVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SEVServiceClient interface {
	CreateSEV(ctx context.Context, in *CreateSEVRequest, opts ...grpc.CallOption) (*SEVResponse, error)
	GetSEV(ctx context.Context, in *GetSEVRequest, opts ...grpc.CallOption) (*SEVResponse, error)
	UpdateSEV(ctx context.Context, in *UpdateSEVRequest, opts ...grpc.CallOption) (*SEVResponse, error)
	ListSEVs(ctx context.Context, in *ListSEVsRequest, opts ...grpc.CallOption) (*ListSEVsResponse, error)
	TransitionStatus(ctx context.Context, in *TransitionStatusRequest, opts ...grpc.CallOption) (*SEVResponse, error)
}

type sEVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSEVServiceClient(cc grpc.ClientConnInterface) SEVServiceClient {
	return &sEVServiceClient{cc}
}

func (c *sEVServiceClient) CreateSEV(ctx context.Context, in *CreateSEVRequest, opts ...grpc.CallOption) (*SEVResponse, error) {
	out := new(SEVResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.SEVService/CreateSEV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sEVServiceClient) GetSEV(ctx context.Context, in *GetSEVRequest, opts ...grpc.CallOption) (*SEVResponse, error) {
	out := new(SEVResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.SEVService/GetSEV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sEVServiceClient) UpdateSEV(ctx context.Context, in *UpdateSEVRequest, opts ...grpc.CallOption) (*SEVResponse, error) {
	out := new(SEVResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.SEVService/UpdateSEV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sEVServiceClient) ListSEVs(ctx context.Context, in *ListSEVsRequest, opts ...grpc.CallOption) (*ListSEVsResponse, error) {
	out := new(ListSEVsResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.SEVService/ListSEVs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sEVServiceClient) TransitionStatus(ctx context.Context, in *TransitionStatusRequest, opts ...grpc.CallOption) (*SEVResponse, error) {
	out := new(SEVResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.SEVService/TransitionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SEVServiceServer is the server API for SEVService service.
// All implementations must embed UnimplementedSEVServiceServer
// for forward compatibility
type SEVServiceServer interface {
	CreateSEV(context.Context, *CreateSEVRequest) (*SEVResponse, error)
	GetSEV(context.Context, *GetSEVRequest) (*SEVResponse, error)
	UpdateSEV(context.Context, *UpdateSEVRequest) (*SEVResponse, error)
	ListSEVs(context.Context, *ListSEVsRequest) (*ListSEVsResponse, error)
	TransitionStatus(context.Context, *TransitionStatusRequest) (*SEVResponse, error)
	mustEmbedUnimplementedSEVServiceServer()
}

// UnimplementedSEVServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSEVServiceServer struct {
}

func (UnimplementedSEVServiceServer) CreateSEV(context.Context, *CreateSEVRequest) (*SEVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSEV not implemented")
}
func (UnimplementedSEVServiceServer) GetSEV(context.Context, *GetSEVRequest) (*SEVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSEV not implemented")
}
func (UnimplementedSEVServiceServer) UpdateSEV(context.Context, *UpdateSEVRequest) (*SEVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSEV not implemented")
}
func (UnimplementedSEVServiceServer) ListSEVs(context.Context, *ListSEVsRequest) (*ListSEVsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSEVs not implemented")
}
func (UnimplementedSEVServiceServer) TransitionStatus(context.Context, *TransitionStatusRequest) (*SEVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionStatus not implemented")
}
func (UnimplementedSEVServiceServer) mustEmbedUnimplementedSEVServiceServer() {}

// UnsafeSEVServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SEVServiceServer will
// result in compilation errors.
type UnsafeSEVServiceServer interface {
	mustEmbedUnimplementedSEVServiceServer()
}

func RegisterSEVServiceServer(s grpc.ServiceRegistrar, srv SEVServiceServer) {
	s.RegisterService(&SEVService_ServiceDesc, srv)
}

func _SEVService_CreateSEV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSEVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SEVServiceServer).CreateSEV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.SEVService/CreateSEV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SEVServiceServer).CreateSEV(ctx, req.(*CreateSEVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SEVService_GetSEV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSEVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SEVServiceServer).GetSEV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.SEVService/GetSEV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SEVServiceServer).GetSEV(ctx, req.(*GetSEVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SEVService_UpdateSEV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSEVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SEVServiceServer).UpdateSEV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.SEVService/UpdateSEV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SEVServiceServer).UpdateSEV(ctx, req.(*UpdateSEVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SEVService_ListSEVs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSEVsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SEVServiceServer).ListSEVs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.SEVService/ListSEVs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SEVServiceServer).ListSEVs(ctx, req.(*ListSEVsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SEVService_TransitionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SEVServiceServer).TransitionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.SEVService/TransitionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SEVServiceServer).TransitionStatus(ctx, req.(*TransitionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SEVService_ServiceDesc is the grpc.ServiceDesc for SEVService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SEVService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sevitout.v1.SEVService",
	HandlerType: (*SEVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSEV",
			Handler:    _SEVService_CreateSEV_Handler,
		},
		{
			MethodName: "GetSEV",
			Handler:    _SEVService_GetSEV_Handler,
		},
		{
			MethodName: "UpdateSEV",
			Handler:    _SEVService_UpdateSEV_Handler,
		},
		{
			MethodName: "ListSEVs",
			Handler:    _SEVService_ListSEVs_Handler,
		},
		{
			MethodName: "TransitionStatus",
			Handler:    _SEVService_TransitionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sevitout/v1/sev.proto",
}
