// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sevitout/v1/sev_link.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SEVLinkServiceClient is the client API for SEVLinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SEVLinkServiceClient interface {
	LinkSEVs(ctx context.Context, in *LinkSEVsRequest, opts ...grpc.CallOption) (*SEVLinkResponse, error)
	UnlinkSEVs(ctx context.Context, in *UnlinkSEVsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListLinkedSEVs(ctx context.Context, in *ListLinkedSEVsRequest, opts ...grpc.CallOption) (*ListLinkedSEVsResponse, error)
}

type sEVLinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSEVLinkServiceClient(cc grpc.ClientConnInterface) SEVLinkServiceClient {
	return &sEVLinkServiceClient{cc}
}

func (c *sEVLinkServiceClient) LinkSEVs(ctx context.Context, in *LinkSEVsRequest, opts ...grpc.CallOption) (*SEVLinkResponse, error) {
	out := new(SEVLinkResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.SEVLinkService/LinkSEVs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sEVLinkServiceClient) UnlinkSEVs(ctx context.Context, in *UnlinkSEVsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/sevitout.v1.SEVLinkService/UnlinkSEVs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sEVLinkServiceClient) ListLinkedSEVs(ctx context.Context, in *ListLinkedSEVsRequest, opts ...grpc.CallOption) (*ListLinkedSEVsResponse, error) {
	out := new(ListLinkedSEVsResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.SEVLinkService/ListLinkedSEVs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SEVLinkServiceServer is the server API for SEVLinkService service.
// All implementations must embed UnimplementedSEVLinkServiceServer
// for forward compatibility
type SEVLinkServiceServer interface {
	LinkSEVs(context.Context, *LinkSEVsRequest) (*SEVLinkResponse, error)
	UnlinkSEVs(context.Context, *UnlinkSEVsRequest) (*emptypb.Empty, error)
	ListLinkedSEVs(context.Context, *ListLinkedSEVsRequest) (*ListLinkedSEVsResponse, error)
	mustEmbedUnimplementedSEVLinkServiceServer()
}

// UnimplementedSEVLinkServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSEVLinkServiceServer struct {
}

func (UnimplementedSEVLinkServiceServer) LinkSEVs(context.Context, *LinkSEVsRequest) (*SEVLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkSEVs not implemented")
}
func (UnimplementedSEVLinkServiceServer) UnlinkSEVs(context.Context, *UnlinkSEVsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlinkSEVs not implemented")
}
func (UnimplementedSEVLinkServiceServer) ListLinkedSEVs(context.Context, *ListLinkedSEVsRequest) (*ListLinkedSEVsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLinkedSEVs not implemented")
}
func (UnimplementedSEVLinkServiceServer) mustEmbedUnimplementedSEVLinkServiceServer() {}

// UnsafeSEVLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SEVLinkServiceServer will
// result in compilation errors.
type UnsafeSEVLinkServiceServer interface {
	mustEmbedUnimplementedSEVLinkServiceServer()
}

func RegisterSEVLinkServiceServer(s grpc.ServiceRegistrar, srv SEVLinkServiceServer) {
	s.RegisterService(&SEVLinkService_ServiceDesc, srv)
}

func _SEVLinkService_LinkSEVs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkSEVsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SEVLinkServiceServer).LinkSEVs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.SEVLinkService/LinkSEVs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SEVLinkServiceServer).LinkSEVs(ctx, req.(*LinkSEVsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SEVLinkService_UnlinkSEVs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkSEVsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SEVLinkServiceServer).UnlinkSEVs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.SEVLinkService/UnlinkSEVs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SEVLinkServiceServer).UnlinkSEVs(ctx, req.(*UnlinkSEVsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SEVLinkService_ListLinkedSEVs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinkedSEVsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SEVLinkServiceServer).ListLinkedSEVs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.SEVLinkService/ListLinkedSEVs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SEVLinkServiceServer).ListLinkedSEVs(ctx, req.(*ListLinkedSEVsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SEVLinkService_ServiceDesc is the grpc.ServiceDesc for SEVLinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SEVLinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sevitout.v1.SEVLinkService",
	HandlerType: (*SEVLinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LinkSEVs",
			Handler:    _SEVLinkService_LinkSEVs_Handler,
		},
		{
			MethodName: "UnlinkSEVs",
			Handler:    _SEVLinkService_UnlinkSEVs_Handler,
		},
		{
			MethodName: "ListLinkedSEVs",
			Handler:    _SEVLinkService_ListLinkedSEVs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sevitout/v1/sev_link.proto",
}
