// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sevitout/v1/sev_access.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SEVAccessServiceClient is the client API for SEVAccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SEVAccessServiceClient interface {
	GrantAccess(ctx context.Context, in *GrantAccessRequest, opts ...grpc.CallOption) (*SEVAccessResponse, error)
	RevokeAccess(ctx context.Context, in *RevokeAccessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListAccess(ctx context.Context, in *ListAccessRequest, opts ...grpc.CallOption) (*ListAccessResponse, error)
}

type sEVAccessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSEVAccessServiceClient(cc grpc.ClientConnInterface) SEVAccessServiceClient {
	return &sEVAccessServiceClient{cc}
}

func (c *sEVAccessServiceClient) GrantAccess(ctx context.Context, in *GrantAccessRequest, opts ...grpc.CallOption) (*SEVAccessResponse, error) {
	out := new(SEVAccessResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.SEVAccessService/GrantAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sEVAccessServiceClient) RevokeAccess(ctx context.Context, in *RevokeAccessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/sevitout.v1.SEVAccessService/RevokeAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sEVAccessServiceClient) ListAccess(ctx context.Context, in *ListAccessRequest, opts ...grpc.CallOption) (*ListAccessResponse, error) {
	out := new(ListAccessResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.SEVAccessService/ListAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SEVAccessServiceServer is the server API for SEVAccessService service.
// All implementations must embed UnimplementedSEVAccessServiceServer
// for forward compatibility
type SEVAccessServiceServer interface {
	GrantAccess(context.Context, *GrantAccessRequest) (*SEVAccessResponse, error)
	RevokeAccess(context.Context, *RevokeAccessRequest) (*emptypb.Empty, error)
	ListAccess(context.Context, *ListAccessRequest) (*ListAccessResponse, error)
	mustEmbedUnimplementedSEVAccessServiceServer()
}

// UnimplementedSEVAccessServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSEVAccessServiceServer struct {
}

func (UnimplementedSEVAccessServiceServer) GrantAccess(context.Context, *GrantAccessRequest) (*SEVAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantAccess not implemented")
}
func (UnimplementedSEVAccessServiceServer) RevokeAccess(context.Context, *RevokeAccessRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeAccess not implemented")
}
func (UnimplementedSEVAccessServiceServer) ListAccess(context.Context, *ListAccessRequest) (*ListAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccess not implemented")
}
func (UnimplementedSEVAccessServiceServer) mustEmbedUnimplementedSEVAccessServiceServer() {}

// UnsafeSEVAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SEVAccessServiceServer will
// result in compilation errors.
type UnsafeSEVAccessServiceServer interface {
	mustEmbedUnimplementedSEVAccessServiceServer()
}

func RegisterSEVAccessServiceServer(s grpc.ServiceRegistrar, srv SEVAccessServiceServer) {
	s.RegisterService(&SEVAccessService_ServiceDesc, srv)
}

func _SEVAccessService_GrantAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SEVAccessServiceServer).GrantAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.SEVAccessService/GrantAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SEVAccessServiceServer).GrantAccess(ctx, req.(*GrantAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SEVAccessService_RevokeAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SEVAccessServiceServer).RevokeAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.SEVAccessService/RevokeAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SEVAccessServiceServer).RevokeAccess(ctx, req.(*RevokeAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SEVAccessService_ListAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SEVAccessServiceServer).ListAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.SEVAccessService/ListAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SEVAccessServiceServer).ListAccess(ctx, req.(*ListAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SEVAccessService_ServiceDesc is the grpc.ServiceDesc for SEVAccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SEVAccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sevitout.v1.SEVAccessService",
	HandlerType: (*SEVAccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrantAccess",
			Handler:    _SEVAccessService_GrantAccess_Handler,
		},
		{
			MethodName: "RevokeAccess",
			Handler:    _SEVAccessService_RevokeAccess_Handler,
		},
		{
			MethodName: "ListAccess",
			Handler:    _SEVAccessService_ListAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sevitout/v1/sev_access.proto",
}
