// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sevitout/v1/task.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	// LinkTask links an existing external task (e.g. a GitHub Issue URL) to a SEV.
	LinkTask(ctx context.Context, in *LinkTaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// UnlinkTask removes a linked task from a SEV by its database ID.
	UnlinkTask(ctx context.Context, in *UnlinkTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListTasks returns all tasks linked to a SEV.
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// UpdateTaskDueDate overrides the SLA-computed due date for a linked task.
	UpdateTaskDueDate(ctx context.Context, in *UpdateTaskDueDateRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// CreateGitHubIssue creates a new GitHub Issue pre-filled with SEV context,
	// links it to the SEV, and returns the linked task record.
	CreateGitHubIssue(ctx context.Context, in *CreateGitHubIssueRequest, opts ...grpc.CallOption) (*TaskResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) LinkTask(ctx context.Context, in *LinkTaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.TaskService/LinkTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UnlinkTask(ctx context.Context, in *UnlinkTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/sevitout.v1.TaskService/UnlinkTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.TaskService/ListTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTaskDueDate(ctx context.Context, in *UpdateTaskDueDateRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.TaskService/UpdateTaskDueDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CreateGitHubIssue(ctx context.Context, in *CreateGitHubIssueRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/sevitout.v1.TaskService/CreateGitHubIssue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility
type TaskServiceServer interface {
	// LinkTask links an existing external task (e.g. a GitHub Issue URL) to a SEV.
	LinkTask(context.Context, *LinkTaskRequest) (*TaskResponse, error)
	// UnlinkTask removes a linked task from a SEV by its database ID.
	UnlinkTask(context.Context, *UnlinkTaskRequest) (*emptypb.Empty, error)
	// ListTasks returns all tasks linked to a SEV.
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// UpdateTaskDueDate overrides the SLA-computed due date for a linked task.
	UpdateTaskDueDate(context.Context, *UpdateTaskDueDateRequest) (*TaskResponse, error)
	// CreateGitHubIssue creates a new GitHub Issue pre-filled with SEV context,
	// links it to the SEV, and returns the linked task record.
	CreateGitHubIssue(context.Context, *CreateGitHubIssueRequest) (*TaskResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (UnimplementedTaskServiceServer) LinkTask(context.Context, *LinkTaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkTask not implemented")
}
func (UnimplementedTaskServiceServer) UnlinkTask(context.Context, *UnlinkTaskRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlinkTask not implemented")
}
func (UnimplementedTaskServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTaskServiceServer) UpdateTaskDueDate(context.Context, *UpdateTaskDueDateRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaskDueDate not implemented")
}
func (UnimplementedTaskServiceServer) CreateGitHubIssue(context.Context, *CreateGitHubIssueRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGitHubIssue not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_LinkTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).LinkTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.TaskService/LinkTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).LinkTask(ctx, req.(*LinkTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UnlinkTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UnlinkTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.TaskService/UnlinkTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UnlinkTask(ctx, req.(*UnlinkTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.TaskService/ListTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTaskDueDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskDueDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTaskDueDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.TaskService/UpdateTaskDueDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTaskDueDate(ctx, req.(*UpdateTaskDueDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CreateGitHubIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGitHubIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateGitHubIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sevitout.v1.TaskService/CreateGitHubIssue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateGitHubIssue(ctx, req.(*CreateGitHubIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sevitout.v1.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LinkTask",
			Handler:    _TaskService_LinkTask_Handler,
		},
		{
			MethodName: "UnlinkTask",
			Handler:    _TaskService_UnlinkTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TaskService_ListTasks_Handler,
		},
		{
			MethodName: "UpdateTaskDueDate",
			Handler:    _TaskService_UpdateTaskDueDate_Handler,
		},
		{
			MethodName: "CreateGitHubIssue",
			Handler:    _TaskService_CreateGitHubIssue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sevitout/v1/task.proto",
}
