// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aioutputs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAIOutput = `-- name: InsertAIOutput :one
INSERT INTO ai_outputs (
    sev_id, plugin_id, trigger_event, action, content, created_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertAIOutputParams struct {
	SevID        string             `json:"sev_id"`
	PluginID     int64              `json:"plugin_id"`
	TriggerEvent string             `json:"trigger_event"`
	Action       string             `json:"action"`
	Content      string             `json:"content"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAIOutput(ctx context.Context, arg InsertAIOutputParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAIOutput,
		arg.SevID,
		arg.PluginID,
		arg.TriggerEvent,
		arg.Action,
		arg.Content,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAIOutputsBySEVID = `-- name: ListAIOutputsBySEVID :many
SELECT id, sev_id, plugin_id, trigger_event, action, content, created_at
FROM ai_outputs
WHERE sev_id = $1
ORDER BY created_at
`

func (q *Queries) ListAIOutputsBySEVID(ctx context.Context, sevID string) ([]AiOutput, error) {
	rows, err := q.db.Query(ctx, listAIOutputsBySEVID, sevID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiOutput
	for rows.Next() {
		var i AiOutput
		if err := rows.Scan(
			&i.ID,
			&i.SevID,
			&i.PluginID,
			&i.TriggerEvent,
			&i.Action,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
