// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aiplugins.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAIPlugin = `-- name: DeleteAIPlugin :exec
DELETE FROM ai_plugins WHERE id = $1
`

func (q *Queries) DeleteAIPlugin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAIPlugin, id)
	return err
}

const getAIPlugin = `-- name: GetAIPlugin :one
SELECT id, name, version, description, handler_type, http_endpoint,
       provider, model, encrypted_api_key, enabled,
       trigger_on_open, trigger_on_mitigated, trigger_on_resolved, trigger_on_postmortem_review,
       rate_limit_per_minute, created_at, updated_at
FROM ai_plugins
WHERE id = $1
`

type GetAIPluginRow struct {
	ID                        int64              `json:"id"`
	Name                      string             `json:"name"`
	Version                   string             `json:"version"`
	Description               *string            `json:"description"`
	HandlerType               string             `json:"handler_type"`
	HttpEndpoint              *string            `json:"http_endpoint"`
	Provider                  *string            `json:"provider"`
	Model                     *string            `json:"model"`
	EncryptedApiKey           []byte             `json:"encrypted_api_key"`
	Enabled                   bool               `json:"enabled"`
	TriggerOnOpen             bool               `json:"trigger_on_open"`
	TriggerOnMitigated        bool               `json:"trigger_on_mitigated"`
	TriggerOnResolved         bool               `json:"trigger_on_resolved"`
	TriggerOnPostmortemReview bool               `json:"trigger_on_postmortem_review"`
	RateLimitPerMinute        int32              `json:"rate_limit_per_minute"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAIPlugin(ctx context.Context, id int64) (GetAIPluginRow, error) {
	row := q.db.QueryRow(ctx, getAIPlugin, id)
	var i GetAIPluginRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.HandlerType,
		&i.HttpEndpoint,
		&i.Provider,
		&i.Model,
		&i.EncryptedApiKey,
		&i.Enabled,
		&i.TriggerOnOpen,
		&i.TriggerOnMitigated,
		&i.TriggerOnResolved,
		&i.TriggerOnPostmortemReview,
		&i.RateLimitPerMinute,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAIPlugin = `-- name: InsertAIPlugin :one
INSERT INTO ai_plugins (
    name, version, description, handler_type, http_endpoint,
    provider, model, encrypted_api_key, enabled,
    trigger_on_open, trigger_on_mitigated, trigger_on_resolved, trigger_on_postmortem_review,
    rate_limit_per_minute, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id
`

type InsertAIPluginParams struct {
	Name                      string             `json:"name"`
	Version                   string             `json:"version"`
	Description               *string            `json:"description"`
	HandlerType               string             `json:"handler_type"`
	HttpEndpoint              *string            `json:"http_endpoint"`
	Provider                  *string            `json:"provider"`
	Model                     *string            `json:"model"`
	EncryptedApiKey           []byte             `json:"encrypted_api_key"`
	Enabled                   bool               `json:"enabled"`
	TriggerOnOpen             bool               `json:"trigger_on_open"`
	TriggerOnMitigated        bool               `json:"trigger_on_mitigated"`
	TriggerOnResolved         bool               `json:"trigger_on_resolved"`
	TriggerOnPostmortemReview bool               `json:"trigger_on_postmortem_review"`
	RateLimitPerMinute        int32              `json:"rate_limit_per_minute"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertAIPlugin(ctx context.Context, arg InsertAIPluginParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAIPlugin,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.HandlerType,
		arg.HttpEndpoint,
		arg.Provider,
		arg.Model,
		arg.EncryptedApiKey,
		arg.Enabled,
		arg.TriggerOnOpen,
		arg.TriggerOnMitigated,
		arg.TriggerOnResolved,
		arg.TriggerOnPostmortemReview,
		arg.RateLimitPerMinute,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAIPlugins = `-- name: ListAIPlugins :many
SELECT id, name, version, description, handler_type, http_endpoint,
       provider, model, encrypted_api_key, enabled,
       trigger_on_open, trigger_on_mitigated, trigger_on_resolved, trigger_on_postmortem_review,
       rate_limit_per_minute, created_at, updated_at
FROM ai_plugins
ORDER BY name
`

type ListAIPluginsRow struct {
	ID                        int64              `json:"id"`
	Name                      string             `json:"name"`
	Version                   string             `json:"version"`
	Description               *string            `json:"description"`
	HandlerType               string             `json:"handler_type"`
	HttpEndpoint              *string            `json:"http_endpoint"`
	Provider                  *string            `json:"provider"`
	Model                     *string            `json:"model"`
	EncryptedApiKey           []byte             `json:"encrypted_api_key"`
	Enabled                   bool               `json:"enabled"`
	TriggerOnOpen             bool               `json:"trigger_on_open"`
	TriggerOnMitigated        bool               `json:"trigger_on_mitigated"`
	TriggerOnResolved         bool               `json:"trigger_on_resolved"`
	TriggerOnPostmortemReview bool               `json:"trigger_on_postmortem_review"`
	RateLimitPerMinute        int32              `json:"rate_limit_per_minute"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAIPlugins(ctx context.Context) ([]ListAIPluginsRow, error) {
	rows, err := q.db.Query(ctx, listAIPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIPluginsRow
	for rows.Next() {
		var i ListAIPluginsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.HandlerType,
			&i.HttpEndpoint,
			&i.Provider,
			&i.Model,
			&i.EncryptedApiKey,
			&i.Enabled,
			&i.TriggerOnOpen,
			&i.TriggerOnMitigated,
			&i.TriggerOnResolved,
			&i.TriggerOnPostmortemReview,
			&i.RateLimitPerMinute,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIPlugin = `-- name: UpdateAIPlugin :exec
UPDATE ai_plugins SET
    name                         = $2,
    version                      = $3,
    description                  = $4,
    handler_type                 = $5,
    http_endpoint                = $6,
    provider                     = $7,
    model                        = $8,
    encrypted_api_key            = $9,
    enabled                      = $10,
    trigger_on_open              = $11,
    trigger_on_mitigated         = $12,
    trigger_on_resolved          = $13,
    trigger_on_postmortem_review = $14,
    rate_limit_per_minute        = $15,
    updated_at                   = $16
WHERE id = $1
`

type UpdateAIPluginParams struct {
	ID                        int64              `json:"id"`
	Name                      string             `json:"name"`
	Version                   string             `json:"version"`
	Description               *string            `json:"description"`
	HandlerType               string             `json:"handler_type"`
	HttpEndpoint              *string            `json:"http_endpoint"`
	Provider                  *string            `json:"provider"`
	Model                     *string            `json:"model"`
	EncryptedApiKey           []byte             `json:"encrypted_api_key"`
	Enabled                   bool               `json:"enabled"`
	TriggerOnOpen             bool               `json:"trigger_on_open"`
	TriggerOnMitigated        bool               `json:"trigger_on_mitigated"`
	TriggerOnResolved         bool               `json:"trigger_on_resolved"`
	TriggerOnPostmortemReview bool               `json:"trigger_on_postmortem_review"`
	RateLimitPerMinute        int32              `json:"rate_limit_per_minute"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAIPlugin(ctx context.Context, arg UpdateAIPluginParams) error {
	_, err := q.db.Exec(ctx, updateAIPlugin,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.HandlerType,
		arg.HttpEndpoint,
		arg.Provider,
		arg.Model,
		arg.EncryptedApiKey,
		arg.Enabled,
		arg.TriggerOnOpen,
		arg.TriggerOnMitigated,
		arg.TriggerOnResolved,
		arg.TriggerOnPostmortemReview,
		arg.RateLimitPerMinute,
		arg.UpdatedAt,
	)
	return err
}
