// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAnnouncement = `-- name: InsertAnnouncement :one
INSERT INTO sev_announcements (sev_id, author_id, message, audience, is_milestone, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertAnnouncementParams struct {
	SevID       string             `json:"sev_id"`
	AuthorID    string             `json:"author_id"`
	Message     string             `json:"message"`
	Audience    string             `json:"audience"`
	IsMilestone bool               `json:"is_milestone"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAnnouncement,
		arg.SevID,
		arg.AuthorID,
		arg.Message,
		arg.Audience,
		arg.IsMilestone,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAnnouncementsBySEVID = `-- name: ListAnnouncementsBySEVID :many
SELECT id, sev_id, author_id, message, audience, is_milestone, created_at
FROM sev_announcements
WHERE sev_id = $1
ORDER BY created_at
`

type ListAnnouncementsBySEVIDRow struct {
	ID          int64              `json:"id"`
	SevID       string             `json:"sev_id"`
	AuthorID    string             `json:"author_id"`
	Message     string             `json:"message"`
	Audience    string             `json:"audience"`
	IsMilestone bool               `json:"is_milestone"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAnnouncementsBySEVID(ctx context.Context, sevID string) ([]ListAnnouncementsBySEVIDRow, error) {
	rows, err := q.db.Query(ctx, listAnnouncementsBySEVID, sevID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnnouncementsBySEVIDRow
	for rows.Next() {
		var i ListAnnouncementsBySEVIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SevID,
			&i.AuthorID,
			&i.Message,
			&i.Audience,
			&i.IsMilestone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAnnouncementSEVIDs = `-- name: SearchAnnouncementSEVIDs :many
SELECT DISTINCT sev_id FROM sev_announcements
WHERE search_vector @@ plainto_tsquery('english', $1::text)
`

// search_vector is a tsvector populated by the tsvector_update_announcements
// trigger (migration 000002); plainto_tsquery tokenizes free-form input
// (implicit AND between words) the same way buildSEVFilterWhere's own
// search-vector query does, so it can't produce a malformed query.
func (q *Queries) SearchAnnouncementSEVIDs(ctx context.Context, dollar_1 string) ([]string, error) {
	rows, err := q.db.Query(ctx, searchAnnouncementSEVIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sev_id string
		if err := rows.Scan(&sev_id); err != nil {
			return nil, err
		}
		items = append(items, sev_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
