// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEntry = `-- name: AppendAuditEntry :one
INSERT INTO audit_log (sev_id, user_id, action, field_name, old_value, new_value, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type AppendAuditEntryParams struct {
	SevID     string             `json:"sev_id"`
	UserID    string             `json:"user_id"`
	Action    string             `json:"action"`
	FieldName *string            `json:"field_name"`
	OldValue  *string            `json:"old_value"`
	NewValue  *string            `json:"new_value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, appendAuditEntry,
		arg.SevID,
		arg.UserID,
		arg.Action,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAuditEntriesBySEVID = `-- name: ListAuditEntriesBySEVID :many
SELECT id, sev_id, user_id, action, field_name, old_value, new_value, created_at
FROM audit_log
WHERE sev_id = $1
ORDER BY created_at
`

func (q *Queries) ListAuditEntriesBySEVID(ctx context.Context, sevID string) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesBySEVID, sevID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.SevID,
			&i.UserID,
			&i.Action,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
