// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertChatEntry = `-- name: InsertChatEntry :one
INSERT INTO sev_chat_log (sev_id, occurred_at, source, author, content, added_at, added_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertChatEntryParams struct {
	SevID      string             `json:"sev_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Source     string             `json:"source"`
	Author     string             `json:"author"`
	Content    string             `json:"content"`
	AddedAt    pgtype.Timestamptz `json:"added_at"`
	AddedBy    string             `json:"added_by"`
}

func (q *Queries) InsertChatEntry(ctx context.Context, arg InsertChatEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChatEntry,
		arg.SevID,
		arg.OccurredAt,
		arg.Source,
		arg.Author,
		arg.Content,
		arg.AddedAt,
		arg.AddedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listChatEntriesBySEVID = `-- name: ListChatEntriesBySEVID :many
SELECT id, sev_id, occurred_at, source, author, content, added_at, added_by
FROM sev_chat_log
WHERE sev_id = $1
ORDER BY occurred_at
`

func (q *Queries) ListChatEntriesBySEVID(ctx context.Context, sevID string) ([]SevChatLog, error) {
	rows, err := q.db.Query(ctx, listChatEntriesBySEVID, sevID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SevChatLog
	for rows.Next() {
		var i SevChatLog
		if err := rows.Scan(
			&i.ID,
			&i.SevID,
			&i.OccurredAt,
			&i.Source,
			&i.Author,
			&i.Content,
			&i.AddedAt,
			&i.AddedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
