// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: escalation_config.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEscalationConfig = `-- name: GetEscalationConfig :one
SELECT id, severity_level, threshold_minutes, enabled, created_at, updated_at
FROM escalation_config
WHERE severity_level = $1
`

func (q *Queries) GetEscalationConfig(ctx context.Context, severityLevel int16) (EscalationConfig, error) {
	row := q.db.QueryRow(ctx, getEscalationConfig, severityLevel)
	var i EscalationConfig
	err := row.Scan(
		&i.ID,
		&i.SeverityLevel,
		&i.ThresholdMinutes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEscalationConfigs = `-- name: ListEscalationConfigs :many
SELECT id, severity_level, threshold_minutes, enabled, created_at, updated_at
FROM escalation_config
ORDER BY severity_level
`

func (q *Queries) ListEscalationConfigs(ctx context.Context) ([]EscalationConfig, error) {
	rows, err := q.db.Query(ctx, listEscalationConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EscalationConfig
	for rows.Next() {
		var i EscalationConfig
		if err := rows.Scan(
			&i.ID,
			&i.SeverityLevel,
			&i.ThresholdMinutes,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEscalationConfig = `-- name: UpsertEscalationConfig :one
INSERT INTO escalation_config (severity_level, threshold_minutes, enabled, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (severity_level) DO UPDATE SET
    threshold_minutes = EXCLUDED.threshold_minutes,
    enabled           = EXCLUDED.enabled,
    updated_at        = NOW()
RETURNING id, created_at, updated_at
`

type UpsertEscalationConfigParams struct {
	SeverityLevel    int16 `json:"severity_level"`
	ThresholdMinutes int32 `json:"threshold_minutes"`
	Enabled          bool  `json:"enabled"`
}

type UpsertEscalationConfigRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertEscalationConfig(ctx context.Context, arg UpsertEscalationConfigParams) (UpsertEscalationConfigRow, error) {
	row := q.db.QueryRow(ctx, upsertEscalationConfig, arg.SeverityLevel, arg.ThresholdMinutes, arg.Enabled)
	var i UpsertEscalationConfigRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
