// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrationconfig.sql

package queries

import (
	"context"
)

const getIntegrationConfig = `-- name: GetIntegrationConfig :one
SELECT id, integration_type, encrypted_credentials, settings, created_at, updated_at
FROM integration_config
WHERE integration_type = $1
`

func (q *Queries) GetIntegrationConfig(ctx context.Context, integrationType string) (IntegrationConfig, error) {
	row := q.db.QueryRow(ctx, getIntegrationConfig, integrationType)
	var i IntegrationConfig
	err := row.Scan(
		&i.ID,
		&i.IntegrationType,
		&i.EncryptedCredentials,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationConfigs = `-- name: ListIntegrationConfigs :many
SELECT id, integration_type, encrypted_credentials, settings, created_at, updated_at
FROM integration_config
ORDER BY integration_type
`

func (q *Queries) ListIntegrationConfigs(ctx context.Context) ([]IntegrationConfig, error) {
	rows, err := q.db.Query(ctx, listIntegrationConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationConfig
	for rows.Next() {
		var i IntegrationConfig
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationType,
			&i.EncryptedCredentials,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIntegrationConfig = `-- name: UpsertIntegrationConfig :one
INSERT INTO integration_config (integration_type, encrypted_credentials, settings, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (integration_type) DO UPDATE SET
    encrypted_credentials = EXCLUDED.encrypted_credentials,
    settings              = EXCLUDED.settings,
    updated_at            = NOW()
RETURNING id
`

type UpsertIntegrationConfigParams struct {
	IntegrationType      string `json:"integration_type"`
	EncryptedCredentials []byte `json:"encrypted_credentials"`
	Settings             []byte `json:"settings"`
}

func (q *Queries) UpsertIntegrationConfig(ctx context.Context, arg UpsertIntegrationConfigParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertIntegrationConfig, arg.IntegrationType, arg.EncryptedCredentials, arg.Settings)
	var id int64
	err := row.Scan(&id)
	return id, err
}
