// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiOutput struct {
	ID           int64              `json:"id"`
	SevID        string             `json:"sev_id"`
	PluginID     int64              `json:"plugin_id"`
	TriggerEvent string             `json:"trigger_event"`
	Action       string             `json:"action"`
	Content      string             `json:"content"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AiPlugin struct {
	ID                        int64              `json:"id"`
	Name                      string             `json:"name"`
	Version                   string             `json:"version"`
	Description               *string            `json:"description"`
	HandlerType               string             `json:"handler_type"`
	HttpEndpoint              *string            `json:"http_endpoint"`
	Provider                  *string            `json:"provider"`
	Model                     *string            `json:"model"`
	EncryptedApiKey           []byte             `json:"encrypted_api_key"`
	Enabled                   bool               `json:"enabled"`
	TriggerOnOpen             bool               `json:"trigger_on_open"`
	TriggerOnMitigated        bool               `json:"trigger_on_mitigated"`
	TriggerOnResolved         bool               `json:"trigger_on_resolved"`
	TriggerOnPostmortemReview bool               `json:"trigger_on_postmortem_review"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	SevID     string             `json:"sev_id"`
	UserID    string             `json:"user_id"`
	Action    string             `json:"action"`
	FieldName *string            `json:"field_name"`
	OldValue  *string            `json:"old_value"`
	NewValue  *string            `json:"new_value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IntegrationConfig struct {
	ID                   int64              `json:"id"`
	IntegrationType      string             `json:"integration_type"`
	EncryptedCredentials []byte             `json:"encrypted_credentials"`
	Settings             []byte             `json:"settings"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type NotificationConfig struct {
	ID            int64              `json:"id"`
	Role          string             `json:"role"`
	Event         string             `json:"event"`
	ChannelType   string             `json:"channel_type"`
	ChannelTarget string             `json:"channel_target"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type OncallRotation struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	ServiceID           *string            `json:"service_id"`
	PagerdutyScheduleID *string            `json:"pagerduty_schedule_id"`
	ManualUserID        *string            `json:"manual_user_id"`
	ManualDisplayName   *string            `json:"manual_display_name"`
	OverrideStart       pgtype.Timestamptz `json:"override_start"`
	OverrideEnd         pgtype.Timestamptz `json:"override_end"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Postmortem struct {
	ID        int64              `json:"id"`
	SevID     string             `json:"sev_id"`
	Status    string             `json:"status"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy *string            `json:"updated_by"`
}

type RetentionConfig struct {
	ID            int64              `json:"id"`
	SeverityLevel int16              `json:"severity_level"`
	RetentionDays int32              `json:"retention_days"`
	HardDelete    bool               `json:"hard_delete"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Description        *string            `json:"description"`
	OwningTeam         *string            `json:"owning_team"`
	PagerdutyServiceID *string            `json:"pagerduty_service_id"`
	Tags               []byte             `json:"tags"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Sev struct {
	ID                    string             `json:"id"`
	Title                 string             `json:"title"`
	Description           string             `json:"description"`
	SeverityLevel         int16              `json:"severity_level"`
	Status                string             `json:"status"`
	RootCauseCategory     *string            `json:"root_cause_category"`
	RootCauseDescription  *string            `json:"root_cause_description"`
	Mitigation            *string            `json:"mitigation"`
	Prevention            *string            `json:"prevention"`
	BusinessImpact        *string            `json:"business_impact"`
	AffectedServices      []string           `json:"affected_services"`
	DetectionMethod       *string            `json:"detection_method"`
	AlertName             *string            `json:"alert_name"`
	MonitoringTool        *string            `json:"monitoring_tool"`
	RightPeoplePresent    *bool              `json:"right_people_present"`
	RightPeopleNotes      *string            `json:"right_people_notes"`
	Tags                  []byte             `json:"tags"`
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	DetectedAt            pgtype.Timestamptz `json:"detected_at"`
	MitigatedAt           pgtype.Timestamptz `json:"mitigated_at"`
	ResolvedAt            pgtype.Timestamptz `json:"resolved_at"`
	PostmortemCompletedAt pgtype.Timestamptz `json:"postmortem_completed_at"`
	MttdSeconds           *int64             `json:"mttd_seconds"`
	MttmSeconds           *int64             `json:"mttm_seconds"`
	MttrSeconds           *int64             `json:"mttr_seconds"`
	DttmSeconds           *int64             `json:"dttm_seconds"`
	Locked                bool               `json:"locked"`
	Sensitive             bool               `json:"sensitive"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CreatedBy             string             `json:"created_by"`
	SearchVector          interface{}        `json:"search_vector"`
}

type SevAnnouncement struct {
	ID           int64              `json:"id"`
	SevID        string             `json:"sev_id"`
	AuthorID     string             `json:"author_id"`
	Message      string             `json:"message"`
	Audience     string             `json:"audience"`
	IsMilestone  bool               `json:"is_milestone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SearchVector interface{}        `json:"search_vector"`
}

type SevChatLog struct {
	ID         int64              `json:"id"`
	SevID      string             `json:"sev_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Source     string             `json:"source"`
	Author     string             `json:"author"`
	Content    string             `json:"content"`
	AddedAt    pgtype.Timestamptz `json:"added_at"`
	AddedBy    string             `json:"added_by"`
}

type SevLink struct {
	ID               int64              `json:"id"`
	SourceSevID      string             `json:"source_sev_id"`
	TargetSevID      string             `json:"target_sev_id"`
	RelationshipType string             `json:"relationship_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CreatedBy        string             `json:"created_by"`
}

type SevLinkedTask struct {
	ID               int64              `json:"id"`
	SevID            string             `json:"sev_id"`
	ExternalSystem   string             `json:"external_system"`
	TaskID           string             `json:"task_id"`
	Url              string             `json:"url"`
	Title            string             `json:"title"`
	Description      *string            `json:"description"`
	RelationshipType string             `json:"relationship_type"`
	Priority         string             `json:"priority"`
	DueDate          pgtype.Date        `json:"due_date"`
	Overdue          bool               `json:"overdue"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CreatedBy        string             `json:"created_by"`
}

type SevRole struct {
	ID          int64              `json:"id"`
	SevID       string             `json:"sev_id"`
	RoleType    string             `json:"role_type"`
	UserID      *string            `json:"user_id"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedBy   string             `json:"created_by"`
}

type SevSli struct {
	ID             int64              `json:"id"`
	SevID          string             `json:"sev_id"`
	ServiceID      *string            `json:"service_id"`
	SliName        string             `json:"sli_name"`
	SloThreshold   string             `json:"slo_threshold"`
	MeasuredValue  string             `json:"measured_value"`
	ViolationStart pgtype.Timestamptz `json:"violation_start"`
	ViolationEnd   pgtype.Timestamptz `json:"violation_end"`
	DashboardUrl   *string            `json:"dashboard_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SevStatusHistory struct {
	ID             int64              `json:"id"`
	SevID          string             `json:"sev_id"`
	FromStatus     *string            `json:"from_status"`
	ToStatus       string             `json:"to_status"`
	UserID         string             `json:"user_id"`
	TransitionedAt pgtype.Timestamptz `json:"transitioned_at"`
}

type ShareableLink struct {
	ID        int64              `json:"id"`
	SevID     string             `json:"sev_id"`
	Token     string             `json:"token"`
	CreatedBy string             `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	RevokedBy *string            `json:"revoked_by"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	AvatarUrl    *string            `json:"avatar_url"`
	OrgRole      string             `json:"org_role"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PasswordHash string             `json:"password_hash"`
}
