// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_config.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationConfig = `-- name: CreateNotificationConfig :one
INSERT INTO notification_config (role, events, channel_type, channel_target, max_severity_level, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, created_at, updated_at
`

type CreateNotificationConfigParams struct {
	Role             string   `json:"role"`
	Events           []string `json:"events"`
	ChannelType      string   `json:"channel_type"`
	ChannelTarget    string   `json:"channel_target"`
	MaxSeverityLevel *int16   `json:"max_severity_level"`
}

type CreateNotificationConfigRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateNotificationConfig(ctx context.Context, arg CreateNotificationConfigParams) (CreateNotificationConfigRow, error) {
	row := q.db.QueryRow(ctx, createNotificationConfig,
		arg.Role,
		arg.Events,
		arg.ChannelType,
		arg.ChannelTarget,
		arg.MaxSeverityLevel,
	)
	var i CreateNotificationConfigRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteNotificationConfig = `-- name: DeleteNotificationConfig :execrows
DELETE FROM notification_config
WHERE id = $1
`

func (q *Queries) DeleteNotificationConfig(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationConfig, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotificationConfigs = `-- name: ListNotificationConfigs :many
SELECT id, role, events, channel_type, channel_target, max_severity_level, created_at, updated_at
FROM notification_config
ORDER BY role, channel_type, id
`

type ListNotificationConfigsRow struct {
	ID               int64              `json:"id"`
	Role             string             `json:"role"`
	Events           []string           `json:"events"`
	ChannelType      string             `json:"channel_type"`
	ChannelTarget    string             `json:"channel_target"`
	MaxSeverityLevel *int16             `json:"max_severity_level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListNotificationConfigs(ctx context.Context) ([]ListNotificationConfigsRow, error) {
	rows, err := q.db.Query(ctx, listNotificationConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationConfigsRow
	for rows.Next() {
		var i ListNotificationConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Events,
			&i.ChannelType,
			&i.ChannelTarget,
			&i.MaxSeverityLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationConfigsForEvent = `-- name: ListNotificationConfigsForEvent :many
SELECT id, role, events, channel_type, channel_target, max_severity_level, created_at, updated_at
FROM notification_config
WHERE $1::text = ANY(events)
  AND (max_severity_level IS NULL OR $2::smallint IS NULL OR max_severity_level >= $2)
ORDER BY role, channel_type
`

type ListNotificationConfigsForEventParams struct {
	Event         string `json:"event"`
	SeverityLevel *int16 `json:"severity_level"`
}

type ListNotificationConfigsForEventRow struct {
	ID               int64              `json:"id"`
	Role             string             `json:"role"`
	Events           []string           `json:"events"`
	ChannelType      string             `json:"channel_type"`
	ChannelTarget    string             `json:"channel_target"`
	MaxSeverityLevel *int16             `json:"max_severity_level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListNotificationConfigsForEvent(ctx context.Context, arg ListNotificationConfigsForEventParams) ([]ListNotificationConfigsForEventRow, error) {
	rows, err := q.db.Query(ctx, listNotificationConfigsForEvent, arg.Event, arg.SeverityLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationConfigsForEventRow
	for rows.Next() {
		var i ListNotificationConfigsForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Events,
			&i.ChannelType,
			&i.ChannelTarget,
			&i.MaxSeverityLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationConfig = `-- name: UpdateNotificationConfig :one
UPDATE notification_config SET
    role                = $2,
    events              = $3,
    channel_type        = $4,
    channel_target      = $5,
    max_severity_level  = $6,
    updated_at          = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at
`

type UpdateNotificationConfigParams struct {
	ID               int64    `json:"id"`
	Role             string   `json:"role"`
	Events           []string `json:"events"`
	ChannelType      string   `json:"channel_type"`
	ChannelTarget    string   `json:"channel_target"`
	MaxSeverityLevel *int16   `json:"max_severity_level"`
}

type UpdateNotificationConfigRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateNotificationConfig(ctx context.Context, arg UpdateNotificationConfigParams) (UpdateNotificationConfigRow, error) {
	row := q.db.QueryRow(ctx, updateNotificationConfig,
		arg.ID,
		arg.Role,
		arg.Events,
		arg.ChannelType,
		arg.ChannelTarget,
		arg.MaxSeverityLevel,
	)
	var i UpdateNotificationConfigRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
