// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_config.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNotificationConfig = `-- name: DeleteNotificationConfig :execrows
DELETE FROM notification_config
WHERE role = $1 AND event = $2 AND channel_type = $3
`

type DeleteNotificationConfigParams struct {
	Role        string `json:"role"`
	Event       string `json:"event"`
	ChannelType string `json:"channel_type"`
}

func (q *Queries) DeleteNotificationConfig(ctx context.Context, arg DeleteNotificationConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationConfig, arg.Role, arg.Event, arg.ChannelType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotificationConfigs = `-- name: ListNotificationConfigs :many
SELECT id, role, event, channel_type, channel_target, max_severity_level, created_at, updated_at
FROM notification_config
ORDER BY role, event, channel_type
`

type ListNotificationConfigsRow struct {
	ID               int64              `json:"id"`
	Role             string             `json:"role"`
	Event            string             `json:"event"`
	ChannelType      string             `json:"channel_type"`
	ChannelTarget    string             `json:"channel_target"`
	MaxSeverityLevel *int16             `json:"max_severity_level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListNotificationConfigs(ctx context.Context) ([]ListNotificationConfigsRow, error) {
	rows, err := q.db.Query(ctx, listNotificationConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationConfigsRow
	for rows.Next() {
		var i ListNotificationConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Event,
			&i.ChannelType,
			&i.ChannelTarget,
			&i.MaxSeverityLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationConfigsForEvent = `-- name: ListNotificationConfigsForEvent :many
SELECT id, role, event, channel_type, channel_target, max_severity_level, created_at, updated_at
FROM notification_config
WHERE event = $1
  AND (max_severity_level IS NULL OR $2::smallint IS NULL OR max_severity_level >= $2)
ORDER BY role, channel_type
`

type ListNotificationConfigsForEventParams struct {
	Event         string `json:"event"`
	SeverityLevel *int16 `json:"severity_level"`
}

type ListNotificationConfigsForEventRow struct {
	ID               int64              `json:"id"`
	Role             string             `json:"role"`
	Event            string             `json:"event"`
	ChannelType      string             `json:"channel_type"`
	ChannelTarget    string             `json:"channel_target"`
	MaxSeverityLevel *int16             `json:"max_severity_level"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListNotificationConfigsForEvent(ctx context.Context, arg ListNotificationConfigsForEventParams) ([]ListNotificationConfigsForEventRow, error) {
	rows, err := q.db.Query(ctx, listNotificationConfigsForEvent, arg.Event, arg.SeverityLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationConfigsForEventRow
	for rows.Next() {
		var i ListNotificationConfigsForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Event,
			&i.ChannelType,
			&i.ChannelTarget,
			&i.MaxSeverityLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotificationConfig = `-- name: UpsertNotificationConfig :one
INSERT INTO notification_config (role, event, channel_type, channel_target, max_severity_level, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (role, event, channel_type) DO UPDATE SET
    channel_target     = EXCLUDED.channel_target,
    max_severity_level = EXCLUDED.max_severity_level,
    updated_at         = NOW()
RETURNING id, created_at, updated_at
`

type UpsertNotificationConfigParams struct {
	Role             string `json:"role"`
	Event            string `json:"event"`
	ChannelType      string `json:"channel_type"`
	ChannelTarget    string `json:"channel_target"`
	MaxSeverityLevel *int16 `json:"max_severity_level"`
}

type UpsertNotificationConfigRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertNotificationConfig(ctx context.Context, arg UpsertNotificationConfigParams) (UpsertNotificationConfigRow, error) {
	row := q.db.QueryRow(ctx, upsertNotificationConfig,
		arg.Role,
		arg.Event,
		arg.ChannelType,
		arg.ChannelTarget,
		arg.MaxSeverityLevel,
	)
	var i UpsertNotificationConfigRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
