// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oncall.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOnCallRotation = `-- name: DeleteOnCallRotation :exec
DELETE FROM oncall_rotations WHERE id = $1
`

func (q *Queries) DeleteOnCallRotation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOnCallRotation, id)
	return err
}

const getCurrentOnCallForService = `-- name: GetCurrentOnCallForService :one
SELECT id, name, service_id, pagerduty_schedule_id,
       manual_user_id, manual_display_name,
       override_start, override_end,
       created_at, updated_at
FROM oncall_rotations
WHERE service_id = $1
  AND (
      -- prefer active manual override window
      (manual_user_id IS NOT NULL AND override_start <= NOW() AND override_end >= NOW())
      OR
      -- fall back to any rotation for this service
      (manual_user_id IS NULL OR override_start IS NULL OR override_end IS NULL)
  )
ORDER BY
    CASE WHEN manual_user_id IS NOT NULL AND override_start <= NOW() AND override_end >= NOW() THEN 0 ELSE 1 END,
    created_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentOnCallForService(ctx context.Context, serviceID *string) (OncallRotation, error) {
	row := q.db.QueryRow(ctx, getCurrentOnCallForService, serviceID)
	var i OncallRotation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServiceID,
		&i.PagerdutyScheduleID,
		&i.ManualUserID,
		&i.ManualDisplayName,
		&i.OverrideStart,
		&i.OverrideEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOnCallRotation = `-- name: GetOnCallRotation :one
SELECT id, name, service_id, pagerduty_schedule_id,
       manual_user_id, manual_display_name,
       override_start, override_end,
       created_at, updated_at
FROM oncall_rotations
WHERE id = $1
`

func (q *Queries) GetOnCallRotation(ctx context.Context, id int64) (OncallRotation, error) {
	row := q.db.QueryRow(ctx, getOnCallRotation, id)
	var i OncallRotation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServiceID,
		&i.PagerdutyScheduleID,
		&i.ManualUserID,
		&i.ManualDisplayName,
		&i.OverrideStart,
		&i.OverrideEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOnCallRotation = `-- name: InsertOnCallRotation :one
INSERT INTO oncall_rotations (
    name, service_id, pagerduty_schedule_id,
    manual_user_id, manual_display_name,
    override_start, override_end,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertOnCallRotationParams struct {
	Name                string             `json:"name"`
	ServiceID           *string            `json:"service_id"`
	PagerdutyScheduleID *string            `json:"pagerduty_schedule_id"`
	ManualUserID        *string            `json:"manual_user_id"`
	ManualDisplayName   *string            `json:"manual_display_name"`
	OverrideStart       pgtype.Timestamptz `json:"override_start"`
	OverrideEnd         pgtype.Timestamptz `json:"override_end"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertOnCallRotation(ctx context.Context, arg InsertOnCallRotationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOnCallRotation,
		arg.Name,
		arg.ServiceID,
		arg.PagerdutyScheduleID,
		arg.ManualUserID,
		arg.ManualDisplayName,
		arg.OverrideStart,
		arg.OverrideEnd,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listOnCallRotations = `-- name: ListOnCallRotations :many
SELECT id, name, service_id, pagerduty_schedule_id,
       manual_user_id, manual_display_name,
       override_start, override_end,
       created_at, updated_at
FROM oncall_rotations
ORDER BY name
`

func (q *Queries) ListOnCallRotations(ctx context.Context) ([]OncallRotation, error) {
	rows, err := q.db.Query(ctx, listOnCallRotations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OncallRotation
	for rows.Next() {
		var i OncallRotation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ServiceID,
			&i.PagerdutyScheduleID,
			&i.ManualUserID,
			&i.ManualDisplayName,
			&i.OverrideStart,
			&i.OverrideEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOnCallRotation = `-- name: UpdateOnCallRotation :exec
UPDATE oncall_rotations SET
    name                  = $2,
    service_id            = $3,
    pagerduty_schedule_id = $4,
    manual_user_id        = $5,
    manual_display_name   = $6,
    override_start        = $7,
    override_end          = $8,
    updated_at            = $9
WHERE id = $1
`

type UpdateOnCallRotationParams struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	ServiceID           *string            `json:"service_id"`
	PagerdutyScheduleID *string            `json:"pagerduty_schedule_id"`
	ManualUserID        *string            `json:"manual_user_id"`
	ManualDisplayName   *string            `json:"manual_display_name"`
	OverrideStart       pgtype.Timestamptz `json:"override_start"`
	OverrideEnd         pgtype.Timestamptz `json:"override_end"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOnCallRotation(ctx context.Context, arg UpdateOnCallRotationParams) error {
	_, err := q.db.Exec(ctx, updateOnCallRotation,
		arg.ID,
		arg.Name,
		arg.ServiceID,
		arg.PagerdutyScheduleID,
		arg.ManualUserID,
		arg.ManualDisplayName,
		arg.OverrideStart,
		arg.OverrideEnd,
		arg.UpdatedAt,
	)
	return err
}
