// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postmortems.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPostmortemBySEVID = `-- name: GetPostmortemBySEVID :one
SELECT id, sev_id, status, content, created_at, updated_at, updated_by
FROM postmortems
WHERE sev_id = $1
`

func (q *Queries) GetPostmortemBySEVID(ctx context.Context, sevID string) (Postmortem, error) {
	row := q.db.QueryRow(ctx, getPostmortemBySEVID, sevID)
	var i Postmortem
	err := row.Scan(
		&i.ID,
		&i.SevID,
		&i.Status,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const insertPostmortem = `-- name: InsertPostmortem :one
INSERT INTO postmortems (sev_id, status, content, created_at, updated_at, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertPostmortemParams struct {
	SevID     string             `json:"sev_id"`
	Status    string             `json:"status"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy *string            `json:"updated_by"`
}

func (q *Queries) InsertPostmortem(ctx context.Context, arg InsertPostmortemParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPostmortem,
		arg.SevID,
		arg.Status,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updatePostmortem = `-- name: UpdatePostmortem :exec
UPDATE postmortems SET
    status     = $2,
    content    = $3,
    updated_at = $4,
    updated_by = $5
WHERE sev_id = $1
`

type UpdatePostmortemParams struct {
	SevID     string             `json:"sev_id"`
	Status    string             `json:"status"`
	Content   string             `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy *string            `json:"updated_by"`
}

func (q *Queries) UpdatePostmortem(ctx context.Context, arg UpdatePostmortemParams) error {
	_, err := q.db.Exec(ctx, updatePostmortem,
		arg.SevID,
		arg.Status,
		arg.Content,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}
