// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retentionconfig.sql

package queries

import (
	"context"
)

const getRetentionConfig = `-- name: GetRetentionConfig :one
SELECT id, severity_level, retention_days, hard_delete, created_at, updated_at
FROM retention_config
WHERE severity_level = $1
`

func (q *Queries) GetRetentionConfig(ctx context.Context, severityLevel int16) (RetentionConfig, error) {
	row := q.db.QueryRow(ctx, getRetentionConfig, severityLevel)
	var i RetentionConfig
	err := row.Scan(
		&i.ID,
		&i.SeverityLevel,
		&i.RetentionDays,
		&i.HardDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRetentionConfig = `-- name: ListRetentionConfig :many
SELECT id, severity_level, retention_days, hard_delete, created_at, updated_at
FROM retention_config
ORDER BY severity_level
`

func (q *Queries) ListRetentionConfig(ctx context.Context) ([]RetentionConfig, error) {
	rows, err := q.db.Query(ctx, listRetentionConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetentionConfig
	for rows.Next() {
		var i RetentionConfig
		if err := rows.Scan(
			&i.ID,
			&i.SeverityLevel,
			&i.RetentionDays,
			&i.HardDelete,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRetentionConfig = `-- name: UpsertRetentionConfig :one
INSERT INTO retention_config (severity_level, retention_days, hard_delete, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (severity_level) DO UPDATE SET
    retention_days = EXCLUDED.retention_days,
    hard_delete    = EXCLUDED.hard_delete,
    updated_at     = NOW()
RETURNING id
`

type UpsertRetentionConfigParams struct {
	SeverityLevel int16 `json:"severity_level"`
	RetentionDays int32 `json:"retention_days"`
	HardDelete    bool  `json:"hard_delete"`
}

func (q *Queries) UpsertRetentionConfig(ctx context.Context, arg UpsertRetentionConfigParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertRetentionConfig, arg.SeverityLevel, arg.RetentionDays, arg.HardDelete)
	var id int64
	err := row.Scan(&id)
	return id, err
}
