// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSEVRole = `-- name: DeleteSEVRole :execresult
DELETE FROM sev_roles WHERE id = $1 AND sev_id = $2
`

type DeleteSEVRoleParams struct {
	ID    int64  `json:"id"`
	SevID string `json:"sev_id"`
}

func (q *Queries) DeleteSEVRole(ctx context.Context, arg DeleteSEVRoleParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteSEVRole, arg.ID, arg.SevID)
}

const insertSEVRole = `-- name: InsertSEVRole :one
INSERT INTO sev_roles (sev_id, role_type, user_id, display_name, created_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertSEVRoleParams struct {
	SevID       string             `json:"sev_id"`
	RoleType    string             `json:"role_type"`
	UserID      *string            `json:"user_id"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedBy   string             `json:"created_by"`
}

func (q *Queries) InsertSEVRole(ctx context.Context, arg InsertSEVRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSEVRole,
		arg.SevID,
		arg.RoleType,
		arg.UserID,
		arg.DisplayName,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRolesBySEVID = `-- name: ListRolesBySEVID :many
SELECT id, sev_id, role_type, user_id, display_name, created_at, created_by
FROM sev_roles
WHERE sev_id = $1
ORDER BY created_at
`

func (q *Queries) ListRolesBySEVID(ctx context.Context, sevID string) ([]SevRole, error) {
	rows, err := q.db.Query(ctx, listRolesBySEVID, sevID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SevRole
	for rows.Next() {
		var i SevRole
		if err := rows.Scan(
			&i.ID,
			&i.SevID,
			&i.RoleType,
			&i.UserID,
			&i.DisplayName,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
