// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getService = `-- name: GetService :one
SELECT id, name, description, owning_team, pagerduty_service_id, tags, active, created_at, updated_at
FROM services
WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id string) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwningTeam,
		&i.PagerdutyServiceID,
		&i.Tags,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertService = `-- name: InsertService :exec
INSERT INTO services (id, name, description, owning_team, pagerduty_service_id, tags, active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertServiceParams struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Description        *string            `json:"description"`
	OwningTeam         *string            `json:"owning_team"`
	PagerdutyServiceID *string            `json:"pagerduty_service_id"`
	Tags               []byte             `json:"tags"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertService(ctx context.Context, arg InsertServiceParams) error {
	_, err := q.db.Exec(ctx, insertService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwningTeam,
		arg.PagerdutyServiceID,
		arg.Tags,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listActiveServices = `-- name: ListActiveServices :many
SELECT id, name, description, owning_team, pagerduty_service_id, tags, active, created_at, updated_at
FROM services
WHERE active = true
ORDER BY name
`

func (q *Queries) ListActiveServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listActiveServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwningTeam,
			&i.PagerdutyServiceID,
			&i.Tags,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, name, description, owning_team, pagerduty_service_id, tags, active, created_at, updated_at
FROM services
ORDER BY name
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwningTeam,
			&i.PagerdutyServiceID,
			&i.Tags,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :exec
UPDATE services SET
    name                 = $2,
    description          = $3,
    owning_team          = $4,
    pagerduty_service_id = $5,
    tags                 = $6,
    active               = $7,
    updated_at           = $8
WHERE id = $1
`

type UpdateServiceParams struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Description        *string            `json:"description"`
	OwningTeam         *string            `json:"owning_team"`
	PagerdutyServiceID *string            `json:"pagerduty_service_id"`
	Tags               []byte             `json:"tags"`
	Active             bool               `json:"active"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.Exec(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwningTeam,
		arg.PagerdutyServiceID,
		arg.Tags,
		arg.Active,
		arg.UpdatedAt,
	)
	return err
}
