// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_slas.sql

package queries

import (
	"context"
)

const deleteServiceSLA = `-- name: DeleteServiceSLA :exec
DELETE FROM service_slas
WHERE service_id = $1 AND severity_level = $2
`

type DeleteServiceSLAParams struct {
	ServiceID     string `json:"service_id"`
	SeverityLevel int16  `json:"severity_level"`
}

func (q *Queries) DeleteServiceSLA(ctx context.Context, arg DeleteServiceSLAParams) error {
	_, err := q.db.Exec(ctx, deleteServiceSLA, arg.ServiceID, arg.SeverityLevel)
	return err
}

const getServiceSLA = `-- name: GetServiceSLA :one
SELECT id, service_id, severity_level, mttd_target_seconds, mttm_target_seconds, mttr_target_seconds, created_at, updated_at
FROM service_slas
WHERE service_id = $1 AND severity_level = $2
`

type GetServiceSLAParams struct {
	ServiceID     string `json:"service_id"`
	SeverityLevel int16  `json:"severity_level"`
}

func (q *Queries) GetServiceSLA(ctx context.Context, arg GetServiceSLAParams) (ServiceSla, error) {
	row := q.db.QueryRow(ctx, getServiceSLA, arg.ServiceID, arg.SeverityLevel)
	var i ServiceSla
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.SeverityLevel,
		&i.MttdTargetSeconds,
		&i.MttmTargetSeconds,
		&i.MttrTargetSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceSLAsByService = `-- name: ListServiceSLAsByService :many
SELECT id, service_id, severity_level, mttd_target_seconds, mttm_target_seconds, mttr_target_seconds, created_at, updated_at
FROM service_slas
WHERE service_id = $1
ORDER BY severity_level
`

func (q *Queries) ListServiceSLAsByService(ctx context.Context, serviceID string) ([]ServiceSla, error) {
	rows, err := q.db.Query(ctx, listServiceSLAsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceSla
	for rows.Next() {
		var i ServiceSla
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.SeverityLevel,
			&i.MttdTargetSeconds,
			&i.MttmTargetSeconds,
			&i.MttrTargetSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceSLAsForServices = `-- name: ListServiceSLAsForServices :many
SELECT id, service_id, severity_level, mttd_target_seconds, mttm_target_seconds, mttr_target_seconds, created_at, updated_at
FROM service_slas
WHERE service_id = ANY($1::text[]) AND severity_level = $2
`

type ListServiceSLAsForServicesParams struct {
	Column1       []string `json:"column_1"`
	SeverityLevel int16    `json:"severity_level"`
}

func (q *Queries) ListServiceSLAsForServices(ctx context.Context, arg ListServiceSLAsForServicesParams) ([]ServiceSla, error) {
	rows, err := q.db.Query(ctx, listServiceSLAsForServices, arg.Column1, arg.SeverityLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceSla
	for rows.Next() {
		var i ServiceSla
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.SeverityLevel,
			&i.MttdTargetSeconds,
			&i.MttmTargetSeconds,
			&i.MttrTargetSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertServiceSLA = `-- name: UpsertServiceSLA :one
INSERT INTO service_slas (service_id, severity_level, mttd_target_seconds, mttm_target_seconds, mttr_target_seconds, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (service_id, severity_level) DO UPDATE SET
    mttd_target_seconds = EXCLUDED.mttd_target_seconds,
    mttm_target_seconds = EXCLUDED.mttm_target_seconds,
    mttr_target_seconds = EXCLUDED.mttr_target_seconds,
    updated_at           = NOW()
RETURNING id
`

type UpsertServiceSLAParams struct {
	ServiceID         string `json:"service_id"`
	SeverityLevel     int16  `json:"severity_level"`
	MttdTargetSeconds *int64 `json:"mttd_target_seconds"`
	MttmTargetSeconds *int64 `json:"mttm_target_seconds"`
	MttrTargetSeconds *int64 `json:"mttr_target_seconds"`
}

func (q *Queries) UpsertServiceSLA(ctx context.Context, arg UpsertServiceSLAParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertServiceSLA,
		arg.ServiceID,
		arg.SeverityLevel,
		arg.MttdTargetSeconds,
		arg.MttmTargetSeconds,
		arg.MttrTargetSeconds,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
