// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_leveling_criteria.sql

package queries

import (
	"context"
)

const deleteServiceLevelingCriteria = `-- name: DeleteServiceLevelingCriteria :exec
DELETE FROM service_leveling_criteria
WHERE service_id = $1 AND severity_level = $2
`

type DeleteServiceLevelingCriteriaParams struct {
	ServiceID     string `json:"service_id"`
	SeverityLevel int16  `json:"severity_level"`
}

func (q *Queries) DeleteServiceLevelingCriteria(ctx context.Context, arg DeleteServiceLevelingCriteriaParams) error {
	_, err := q.db.Exec(ctx, deleteServiceLevelingCriteria, arg.ServiceID, arg.SeverityLevel)
	return err
}

const getServiceLevelingCriteria = `-- name: GetServiceLevelingCriteria :one
SELECT id, service_id, severity_level, criteria, created_at, updated_at
FROM service_leveling_criteria
WHERE service_id = $1 AND severity_level = $2
`

type GetServiceLevelingCriteriaParams struct {
	ServiceID     string `json:"service_id"`
	SeverityLevel int16  `json:"severity_level"`
}

func (q *Queries) GetServiceLevelingCriteria(ctx context.Context, arg GetServiceLevelingCriteriaParams) (ServiceLevelingCriterium, error) {
	row := q.db.QueryRow(ctx, getServiceLevelingCriteria, arg.ServiceID, arg.SeverityLevel)
	var i ServiceLevelingCriterium
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.SeverityLevel,
		&i.Criteria,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceLevelingCriteriaByService = `-- name: ListServiceLevelingCriteriaByService :many
SELECT id, service_id, severity_level, criteria, created_at, updated_at
FROM service_leveling_criteria
WHERE service_id = $1
ORDER BY severity_level
`

func (q *Queries) ListServiceLevelingCriteriaByService(ctx context.Context, serviceID string) ([]ServiceLevelingCriterium, error) {
	rows, err := q.db.Query(ctx, listServiceLevelingCriteriaByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceLevelingCriterium
	for rows.Next() {
		var i ServiceLevelingCriterium
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.SeverityLevel,
			&i.Criteria,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceLevelingCriteriaForServices = `-- name: ListServiceLevelingCriteriaForServices :many
SELECT id, service_id, severity_level, criteria, created_at, updated_at
FROM service_leveling_criteria
WHERE service_id = ANY($1::text[]) AND severity_level = $2
`

type ListServiceLevelingCriteriaForServicesParams struct {
	Column1       []string `json:"column_1"`
	SeverityLevel int16    `json:"severity_level"`
}

func (q *Queries) ListServiceLevelingCriteriaForServices(ctx context.Context, arg ListServiceLevelingCriteriaForServicesParams) ([]ServiceLevelingCriterium, error) {
	rows, err := q.db.Query(ctx, listServiceLevelingCriteriaForServices, arg.Column1, arg.SeverityLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceLevelingCriterium
	for rows.Next() {
		var i ServiceLevelingCriterium
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.SeverityLevel,
			&i.Criteria,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertServiceLevelingCriteria = `-- name: UpsertServiceLevelingCriteria :one
INSERT INTO service_leveling_criteria (service_id, severity_level, criteria, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (service_id, severity_level) DO UPDATE SET
    criteria   = EXCLUDED.criteria,
    updated_at = NOW()
RETURNING id
`

type UpsertServiceLevelingCriteriaParams struct {
	ServiceID     string `json:"service_id"`
	SeverityLevel int16  `json:"severity_level"`
	Criteria      string `json:"criteria"`
}

func (q *Queries) UpsertServiceLevelingCriteria(ctx context.Context, arg UpsertServiceLevelingCriteriaParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertServiceLevelingCriteria, arg.ServiceID, arg.SeverityLevel, arg.Criteria)
	var id int64
	err := row.Scan(&id)
	return id, err
}
