// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sev_access.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSEVAccess = `-- name: DeleteSEVAccess :execresult
DELETE FROM sev_access WHERE id = $1 AND sev_id = $2
`

type DeleteSEVAccessParams struct {
	ID    int64  `json:"id"`
	SevID string `json:"sev_id"`
}

func (q *Queries) DeleteSEVAccess(ctx context.Context, arg DeleteSEVAccessParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteSEVAccess, arg.ID, arg.SevID)
}

const insertSEVAccess = `-- name: InsertSEVAccess :one
INSERT INTO sev_access (sev_id, user_id, created_at, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertSEVAccessParams struct {
	SevID     string             `json:"sev_id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy string             `json:"created_by"`
}

func (q *Queries) InsertSEVAccess(ctx context.Context, arg InsertSEVAccessParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSEVAccess,
		arg.SevID,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listSEVAccessBySEVID = `-- name: ListSEVAccessBySEVID :many
SELECT id, sev_id, user_id, created_at, created_by
FROM sev_access
WHERE sev_id = $1
ORDER BY created_at
`

func (q *Queries) ListSEVAccessBySEVID(ctx context.Context, sevID string) ([]SevAccess, error) {
	rows, err := q.db.Query(ctx, listSEVAccessBySEVID, sevID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SevAccess
	for rows.Next() {
		var i SevAccess
		if err := rows.Scan(
			&i.ID,
			&i.SevID,
			&i.UserID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSEVIDsByAccessUser = `-- name: ListSEVIDsByAccessUser :many
SELECT sev_id FROM sev_access WHERE user_id = $1
`

func (q *Queries) ListSEVIDsByAccessUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listSEVIDsByAccessUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sev_id string
		if err := rows.Scan(&sev_id); err != nil {
			return nil, err
		}
		items = append(items, sev_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sEVAccessExists = `-- name: SEVAccessExists :one
SELECT EXISTS(SELECT 1 FROM sev_access WHERE sev_id = $1 AND user_id = $2)
`

type SEVAccessExistsParams struct {
	SevID  string `json:"sev_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SEVAccessExists(ctx context.Context, arg SEVAccessExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sEVAccessExists, arg.SevID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
