// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sevlinks.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSEVLink = `-- name: DeleteSEVLink :exec
DELETE FROM sev_links
WHERE source_sev_id = $1 AND target_sev_id = $2 AND relationship_type = $3
`

type DeleteSEVLinkParams struct {
	SourceSevID      string `json:"source_sev_id"`
	TargetSevID      string `json:"target_sev_id"`
	RelationshipType string `json:"relationship_type"`
}

func (q *Queries) DeleteSEVLink(ctx context.Context, arg DeleteSEVLinkParams) error {
	_, err := q.db.Exec(ctx, deleteSEVLink, arg.SourceSevID, arg.TargetSevID, arg.RelationshipType)
	return err
}

const insertSEVLink = `-- name: InsertSEVLink :one
INSERT INTO sev_links (source_sev_id, target_sev_id, relationship_type, created_at, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertSEVLinkParams struct {
	SourceSevID      string             `json:"source_sev_id"`
	TargetSevID      string             `json:"target_sev_id"`
	RelationshipType string             `json:"relationship_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CreatedBy        string             `json:"created_by"`
}

func (q *Queries) InsertSEVLink(ctx context.Context, arg InsertSEVLinkParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSEVLink,
		arg.SourceSevID,
		arg.TargetSevID,
		arg.RelationshipType,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listSEVLinksBySEVID = `-- name: ListSEVLinksBySEVID :many
SELECT id, source_sev_id, target_sev_id, relationship_type, created_at, created_by
FROM sev_links
WHERE source_sev_id = $1 OR target_sev_id = $1
ORDER BY created_at
`

func (q *Queries) ListSEVLinksBySEVID(ctx context.Context, sourceSevID string) ([]SevLink, error) {
	rows, err := q.db.Query(ctx, listSEVLinksBySEVID, sourceSevID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SevLink
	for rows.Next() {
		var i SevLink
		if err := rows.Scan(
			&i.ID,
			&i.SourceSevID,
			&i.TargetSevID,
			&i.RelationshipType,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
