// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sevs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSEV = `-- name: GetSEV :one
SELECT id, title, description, severity_level, status,
       root_cause_category, root_cause_description, mitigation, prevention,
       business_impact, affected_services, detection_method, alert_name,
       monitoring_tool, alert_url, dashboard_url, query, snapshot_url, github_repo,
       root_cause_reference_url,
       right_people_present, right_people_notes, tags,
       started_at, detected_at, mitigated_at, resolved_at, postmortem_completed_at,
       mttd_seconds, mttm_seconds, mttr_seconds, dttm_seconds,
       locked, sensitive, ai_disabled, created_at, updated_at, created_by,
       slack_channel_id
FROM sevs
WHERE id = $1
`

type GetSEVRow struct {
	ID                    string             `json:"id"`
	Title                 string             `json:"title"`
	Description           string             `json:"description"`
	SeverityLevel         int16              `json:"severity_level"`
	Status                string             `json:"status"`
	RootCauseCategory     *string            `json:"root_cause_category"`
	RootCauseDescription  *string            `json:"root_cause_description"`
	Mitigation            *string            `json:"mitigation"`
	Prevention            *string            `json:"prevention"`
	BusinessImpact        *string            `json:"business_impact"`
	AffectedServices      []string           `json:"affected_services"`
	DetectionMethod       *string            `json:"detection_method"`
	AlertName             *string            `json:"alert_name"`
	MonitoringTool        *string            `json:"monitoring_tool"`
	AlertUrl              *string            `json:"alert_url"`
	DashboardUrl          *string            `json:"dashboard_url"`
	Query                 *string            `json:"query"`
	SnapshotUrl           *string            `json:"snapshot_url"`
	GithubRepo            *string            `json:"github_repo"`
	RootCauseReferenceUrl *string            `json:"root_cause_reference_url"`
	RightPeoplePresent    *bool              `json:"right_people_present"`
	RightPeopleNotes      *string            `json:"right_people_notes"`
	Tags                  []byte             `json:"tags"`
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	DetectedAt            pgtype.Timestamptz `json:"detected_at"`
	MitigatedAt           pgtype.Timestamptz `json:"mitigated_at"`
	ResolvedAt            pgtype.Timestamptz `json:"resolved_at"`
	PostmortemCompletedAt pgtype.Timestamptz `json:"postmortem_completed_at"`
	MttdSeconds           *int64             `json:"mttd_seconds"`
	MttmSeconds           *int64             `json:"mttm_seconds"`
	MttrSeconds           *int64             `json:"mttr_seconds"`
	DttmSeconds           *int64             `json:"dttm_seconds"`
	Locked                bool               `json:"locked"`
	Sensitive             bool               `json:"sensitive"`
	AiDisabled            bool               `json:"ai_disabled"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CreatedBy             string             `json:"created_by"`
	SlackChannelID        *string            `json:"slack_channel_id"`
}

func (q *Queries) GetSEV(ctx context.Context, id string) (GetSEVRow, error) {
	row := q.db.QueryRow(ctx, getSEV, id)
	var i GetSEVRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SeverityLevel,
		&i.Status,
		&i.RootCauseCategory,
		&i.RootCauseDescription,
		&i.Mitigation,
		&i.Prevention,
		&i.BusinessImpact,
		&i.AffectedServices,
		&i.DetectionMethod,
		&i.AlertName,
		&i.MonitoringTool,
		&i.AlertUrl,
		&i.DashboardUrl,
		&i.Query,
		&i.SnapshotUrl,
		&i.GithubRepo,
		&i.RootCauseReferenceUrl,
		&i.RightPeoplePresent,
		&i.RightPeopleNotes,
		&i.Tags,
		&i.StartedAt,
		&i.DetectedAt,
		&i.MitigatedAt,
		&i.ResolvedAt,
		&i.PostmortemCompletedAt,
		&i.MttdSeconds,
		&i.MttmSeconds,
		&i.MttrSeconds,
		&i.DttmSeconds,
		&i.Locked,
		&i.Sensitive,
		&i.AiDisabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.SlackChannelID,
	)
	return i, err
}

const insertSEV = `-- name: InsertSEV :exec
INSERT INTO sevs (
    id, title, description, severity_level, status,
    root_cause_category, root_cause_description, mitigation, prevention,
    business_impact, affected_services, detection_method, alert_name,
    monitoring_tool, alert_url, dashboard_url, query, snapshot_url, github_repo,
    root_cause_reference_url,
    right_people_present, right_people_notes, tags,
    started_at, detected_at, mitigated_at, resolved_at, postmortem_completed_at,
    mttd_seconds, mttm_seconds, mttr_seconds, dttm_seconds,
    locked, sensitive, ai_disabled, created_at, updated_at, created_by,
    slack_channel_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19,
    $20,
    $21, $22, $23,
    $24, $25, $26, $27, $28,
    $29, $30, $31, $32,
    $33, $34, $35, $36, $37, $38,
    $39
)
`

type InsertSEVParams struct {
	ID                    string             `json:"id"`
	Title                 string             `json:"title"`
	Description           string             `json:"description"`
	SeverityLevel         int16              `json:"severity_level"`
	Status                string             `json:"status"`
	RootCauseCategory     *string            `json:"root_cause_category"`
	RootCauseDescription  *string            `json:"root_cause_description"`
	Mitigation            *string            `json:"mitigation"`
	Prevention            *string            `json:"prevention"`
	BusinessImpact        *string            `json:"business_impact"`
	AffectedServices      []string           `json:"affected_services"`
	DetectionMethod       *string            `json:"detection_method"`
	AlertName             *string            `json:"alert_name"`
	MonitoringTool        *string            `json:"monitoring_tool"`
	AlertUrl              *string            `json:"alert_url"`
	DashboardUrl          *string            `json:"dashboard_url"`
	Query                 *string            `json:"query"`
	SnapshotUrl           *string            `json:"snapshot_url"`
	GithubRepo            *string            `json:"github_repo"`
	RootCauseReferenceUrl *string            `json:"root_cause_reference_url"`
	RightPeoplePresent    *bool              `json:"right_people_present"`
	RightPeopleNotes      *string            `json:"right_people_notes"`
	Tags                  []byte             `json:"tags"`
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	DetectedAt            pgtype.Timestamptz `json:"detected_at"`
	MitigatedAt           pgtype.Timestamptz `json:"mitigated_at"`
	ResolvedAt            pgtype.Timestamptz `json:"resolved_at"`
	PostmortemCompletedAt pgtype.Timestamptz `json:"postmortem_completed_at"`
	MttdSeconds           *int64             `json:"mttd_seconds"`
	MttmSeconds           *int64             `json:"mttm_seconds"`
	MttrSeconds           *int64             `json:"mttr_seconds"`
	DttmSeconds           *int64             `json:"dttm_seconds"`
	Locked                bool               `json:"locked"`
	Sensitive             bool               `json:"sensitive"`
	AiDisabled            bool               `json:"ai_disabled"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CreatedBy             string             `json:"created_by"`
	SlackChannelID        *string            `json:"slack_channel_id"`
}

func (q *Queries) InsertSEV(ctx context.Context, arg InsertSEVParams) error {
	_, err := q.db.Exec(ctx, insertSEV,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.SeverityLevel,
		arg.Status,
		arg.RootCauseCategory,
		arg.RootCauseDescription,
		arg.Mitigation,
		arg.Prevention,
		arg.BusinessImpact,
		arg.AffectedServices,
		arg.DetectionMethod,
		arg.AlertName,
		arg.MonitoringTool,
		arg.AlertUrl,
		arg.DashboardUrl,
		arg.Query,
		arg.SnapshotUrl,
		arg.GithubRepo,
		arg.RootCauseReferenceUrl,
		arg.RightPeoplePresent,
		arg.RightPeopleNotes,
		arg.Tags,
		arg.StartedAt,
		arg.DetectedAt,
		arg.MitigatedAt,
		arg.ResolvedAt,
		arg.PostmortemCompletedAt,
		arg.MttdSeconds,
		arg.MttmSeconds,
		arg.MttrSeconds,
		arg.DttmSeconds,
		arg.Locked,
		arg.Sensitive,
		arg.AiDisabled,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.SlackChannelID,
	)
	return err
}

const listSEVs = `-- name: ListSEVs :many
SELECT id, title, description, severity_level, status,
       root_cause_category, root_cause_description, mitigation, prevention,
       business_impact, affected_services, detection_method, alert_name,
       monitoring_tool, alert_url, dashboard_url, query, snapshot_url, github_repo,
       root_cause_reference_url,
       right_people_present, right_people_notes, tags,
       started_at, detected_at, mitigated_at, resolved_at, postmortem_completed_at,
       mttd_seconds, mttm_seconds, mttr_seconds, dttm_seconds,
       locked, sensitive, ai_disabled, created_at, updated_at, created_by,
       slack_channel_id
FROM sevs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSEVsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSEVsRow struct {
	ID                    string             `json:"id"`
	Title                 string             `json:"title"`
	Description           string             `json:"description"`
	SeverityLevel         int16              `json:"severity_level"`
	Status                string             `json:"status"`
	RootCauseCategory     *string            `json:"root_cause_category"`
	RootCauseDescription  *string            `json:"root_cause_description"`
	Mitigation            *string            `json:"mitigation"`
	Prevention            *string            `json:"prevention"`
	BusinessImpact        *string            `json:"business_impact"`
	AffectedServices      []string           `json:"affected_services"`
	DetectionMethod       *string            `json:"detection_method"`
	AlertName             *string            `json:"alert_name"`
	MonitoringTool        *string            `json:"monitoring_tool"`
	AlertUrl              *string            `json:"alert_url"`
	DashboardUrl          *string            `json:"dashboard_url"`
	Query                 *string            `json:"query"`
	SnapshotUrl           *string            `json:"snapshot_url"`
	GithubRepo            *string            `json:"github_repo"`
	RootCauseReferenceUrl *string            `json:"root_cause_reference_url"`
	RightPeoplePresent    *bool              `json:"right_people_present"`
	RightPeopleNotes      *string            `json:"right_people_notes"`
	Tags                  []byte             `json:"tags"`
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	DetectedAt            pgtype.Timestamptz `json:"detected_at"`
	MitigatedAt           pgtype.Timestamptz `json:"mitigated_at"`
	ResolvedAt            pgtype.Timestamptz `json:"resolved_at"`
	PostmortemCompletedAt pgtype.Timestamptz `json:"postmortem_completed_at"`
	MttdSeconds           *int64             `json:"mttd_seconds"`
	MttmSeconds           *int64             `json:"mttm_seconds"`
	MttrSeconds           *int64             `json:"mttr_seconds"`
	DttmSeconds           *int64             `json:"dttm_seconds"`
	Locked                bool               `json:"locked"`
	Sensitive             bool               `json:"sensitive"`
	AiDisabled            bool               `json:"ai_disabled"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CreatedBy             string             `json:"created_by"`
	SlackChannelID        *string            `json:"slack_channel_id"`
}

func (q *Queries) ListSEVs(ctx context.Context, arg ListSEVsParams) ([]ListSEVsRow, error) {
	rows, err := q.db.Query(ctx, listSEVs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSEVsRow
	for rows.Next() {
		var i ListSEVsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.SeverityLevel,
			&i.Status,
			&i.RootCauseCategory,
			&i.RootCauseDescription,
			&i.Mitigation,
			&i.Prevention,
			&i.BusinessImpact,
			&i.AffectedServices,
			&i.DetectionMethod,
			&i.AlertName,
			&i.MonitoringTool,
			&i.AlertUrl,
			&i.DashboardUrl,
			&i.Query,
			&i.SnapshotUrl,
			&i.GithubRepo,
			&i.RootCauseReferenceUrl,
			&i.RightPeoplePresent,
			&i.RightPeopleNotes,
			&i.Tags,
			&i.StartedAt,
			&i.DetectedAt,
			&i.MitigatedAt,
			&i.ResolvedAt,
			&i.PostmortemCompletedAt,
			&i.MttdSeconds,
			&i.MttmSeconds,
			&i.MttrSeconds,
			&i.DttmSeconds,
			&i.Locked,
			&i.Sensitive,
			&i.AiDisabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.SlackChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSEVNumber = `-- name: NextSEVNumber :one
SELECT nextval('sev_number_seq')::bigint AS seq
`

func (q *Queries) NextSEVNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextSEVNumber)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const updateSEV = `-- name: UpdateSEV :exec
UPDATE sevs SET
    title                  = $2,
    description            = $3,
    severity_level         = $4,
    status                 = $5,
    root_cause_category    = $6,
    root_cause_description = $7,
    mitigation             = $8,
    prevention             = $9,
    business_impact        = $10,
    affected_services      = $11,
    detection_method       = $12,
    alert_name             = $13,
    monitoring_tool        = $14,
    alert_url              = $15,
    dashboard_url          = $16,
    query                  = $17,
    snapshot_url           = $18,
    github_repo            = $19,
    root_cause_reference_url = $20,
    right_people_present   = $21,
    right_people_notes     = $22,
    tags                   = $23,
    started_at             = $24,
    detected_at            = $25,
    mitigated_at           = $26,
    resolved_at            = $27,
    postmortem_completed_at = $28,
    mttd_seconds           = $29,
    mttm_seconds           = $30,
    mttr_seconds           = $31,
    dttm_seconds           = $32,
    locked                 = $33,
    sensitive              = $34,
    ai_disabled            = $35,
    updated_at             = $36,
    slack_channel_id       = $37
WHERE id = $1
`

type UpdateSEVParams struct {
	ID                    string             `json:"id"`
	Title                 string             `json:"title"`
	Description           string             `json:"description"`
	SeverityLevel         int16              `json:"severity_level"`
	Status                string             `json:"status"`
	RootCauseCategory     *string            `json:"root_cause_category"`
	RootCauseDescription  *string            `json:"root_cause_description"`
	Mitigation            *string            `json:"mitigation"`
	Prevention            *string            `json:"prevention"`
	BusinessImpact        *string            `json:"business_impact"`
	AffectedServices      []string           `json:"affected_services"`
	DetectionMethod       *string            `json:"detection_method"`
	AlertName             *string            `json:"alert_name"`
	MonitoringTool        *string            `json:"monitoring_tool"`
	AlertUrl              *string            `json:"alert_url"`
	DashboardUrl          *string            `json:"dashboard_url"`
	Query                 *string            `json:"query"`
	SnapshotUrl           *string            `json:"snapshot_url"`
	GithubRepo            *string            `json:"github_repo"`
	RootCauseReferenceUrl *string            `json:"root_cause_reference_url"`
	RightPeoplePresent    *bool              `json:"right_people_present"`
	RightPeopleNotes      *string            `json:"right_people_notes"`
	Tags                  []byte             `json:"tags"`
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	DetectedAt            pgtype.Timestamptz `json:"detected_at"`
	MitigatedAt           pgtype.Timestamptz `json:"mitigated_at"`
	ResolvedAt            pgtype.Timestamptz `json:"resolved_at"`
	PostmortemCompletedAt pgtype.Timestamptz `json:"postmortem_completed_at"`
	MttdSeconds           *int64             `json:"mttd_seconds"`
	MttmSeconds           *int64             `json:"mttm_seconds"`
	MttrSeconds           *int64             `json:"mttr_seconds"`
	DttmSeconds           *int64             `json:"dttm_seconds"`
	Locked                bool               `json:"locked"`
	Sensitive             bool               `json:"sensitive"`
	AiDisabled            bool               `json:"ai_disabled"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	SlackChannelID        *string            `json:"slack_channel_id"`
}

func (q *Queries) UpdateSEV(ctx context.Context, arg UpdateSEVParams) error {
	_, err := q.db.Exec(ctx, updateSEV,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.SeverityLevel,
		arg.Status,
		arg.RootCauseCategory,
		arg.RootCauseDescription,
		arg.Mitigation,
		arg.Prevention,
		arg.BusinessImpact,
		arg.AffectedServices,
		arg.DetectionMethod,
		arg.AlertName,
		arg.MonitoringTool,
		arg.AlertUrl,
		arg.DashboardUrl,
		arg.Query,
		arg.SnapshotUrl,
		arg.GithubRepo,
		arg.RootCauseReferenceUrl,
		arg.RightPeoplePresent,
		arg.RightPeopleNotes,
		arg.Tags,
		arg.StartedAt,
		arg.DetectedAt,
		arg.MitigatedAt,
		arg.ResolvedAt,
		arg.PostmortemCompletedAt,
		arg.MttdSeconds,
		arg.MttmSeconds,
		arg.MttrSeconds,
		arg.DttmSeconds,
		arg.Locked,
		arg.Sensitive,
		arg.AiDisabled,
		arg.UpdatedAt,
		arg.SlackChannelID,
	)
	return err
}

const updateSEVLocked = `-- name: UpdateSEVLocked :exec
UPDATE sevs SET locked = $2, updated_at = NOW() WHERE id = $1
`

type UpdateSEVLockedParams struct {
	ID     string `json:"id"`
	Locked bool   `json:"locked"`
}

func (q *Queries) UpdateSEVLocked(ctx context.Context, arg UpdateSEVLockedParams) error {
	_, err := q.db.Exec(ctx, updateSEVLocked, arg.ID, arg.Locked)
	return err
}
