// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getShareableLinkByToken = `-- name: GetShareableLinkByToken :one
SELECT id, sev_id, token, created_by, expires_at, revoked, revoked_by, revoked_at, created_at
FROM shareable_links
WHERE token = $1
`

func (q *Queries) GetShareableLinkByToken(ctx context.Context, token string) (ShareableLink, error) {
	row := q.db.QueryRow(ctx, getShareableLinkByToken, token)
	var i ShareableLink
	err := row.Scan(
		&i.ID,
		&i.SevID,
		&i.Token,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertShareableLink = `-- name: InsertShareableLink :one
INSERT INTO shareable_links (sev_id, token, created_by, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertShareableLinkParams struct {
	SevID     string             `json:"sev_id"`
	Token     string             `json:"token"`
	CreatedBy string             `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertShareableLink(ctx context.Context, arg InsertShareableLinkParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertShareableLink,
		arg.SevID,
		arg.Token,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listShareableLinksBySEVID = `-- name: ListShareableLinksBySEVID :many
SELECT id, sev_id, token, created_by, expires_at, revoked, revoked_by, revoked_at, created_at
FROM shareable_links
WHERE sev_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListShareableLinksBySEVID(ctx context.Context, sevID string) ([]ShareableLink, error) {
	rows, err := q.db.Query(ctx, listShareableLinksBySEVID, sevID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareableLink
	for rows.Next() {
		var i ShareableLink
		if err := rows.Scan(
			&i.ID,
			&i.SevID,
			&i.Token,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeShareableLink = `-- name: RevokeShareableLink :exec
UPDATE shareable_links SET
    revoked    = true,
    revoked_by = $2,
    revoked_at = NOW()
WHERE token = $1
`

type RevokeShareableLinkParams struct {
	Token     string  `json:"token"`
	RevokedBy *string `json:"revoked_by"`
}

func (q *Queries) RevokeShareableLink(ctx context.Context, arg RevokeShareableLinkParams) error {
	_, err := q.db.Exec(ctx, revokeShareableLink, arg.Token, arg.RevokedBy)
	return err
}
