// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slis.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSLI = `-- name: DeleteSLI :exec
DELETE FROM sev_slis WHERE id = $1
`

func (q *Queries) DeleteSLI(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSLI, id)
	return err
}

const insertSLI = `-- name: InsertSLI :one
INSERT INTO sev_slis (
    sev_id, service_id, sli_name, slo_threshold, measured_value,
    violation_start, violation_end, dashboard_url, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertSLIParams struct {
	SevID          string             `json:"sev_id"`
	ServiceID      *string            `json:"service_id"`
	SliName        string             `json:"sli_name"`
	SloThreshold   string             `json:"slo_threshold"`
	MeasuredValue  string             `json:"measured_value"`
	ViolationStart pgtype.Timestamptz `json:"violation_start"`
	ViolationEnd   pgtype.Timestamptz `json:"violation_end"`
	DashboardUrl   *string            `json:"dashboard_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertSLI(ctx context.Context, arg InsertSLIParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSLI,
		arg.SevID,
		arg.ServiceID,
		arg.SliName,
		arg.SloThreshold,
		arg.MeasuredValue,
		arg.ViolationStart,
		arg.ViolationEnd,
		arg.DashboardUrl,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listSLIsBySEVID = `-- name: ListSLIsBySEVID :many
SELECT id, sev_id, service_id, sli_name, slo_threshold, measured_value,
       violation_start, violation_end, dashboard_url, created_at
FROM sev_slis
WHERE sev_id = $1
ORDER BY created_at
`

func (q *Queries) ListSLIsBySEVID(ctx context.Context, sevID string) ([]SevSli, error) {
	rows, err := q.db.Query(ctx, listSLIsBySEVID, sevID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SevSli
	for rows.Next() {
		var i SevSli
		if err := rows.Scan(
			&i.ID,
			&i.SevID,
			&i.ServiceID,
			&i.SliName,
			&i.SloThreshold,
			&i.MeasuredValue,
			&i.ViolationStart,
			&i.ViolationEnd,
			&i.DashboardUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
