// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_history.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertStatusHistory = `-- name: InsertStatusHistory :one
INSERT INTO sev_status_history (sev_id, from_status, to_status, user_id, transitioned_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertStatusHistoryParams struct {
	SevID          string             `json:"sev_id"`
	FromStatus     *string            `json:"from_status"`
	ToStatus       string             `json:"to_status"`
	UserID         string             `json:"user_id"`
	TransitionedAt pgtype.Timestamptz `json:"transitioned_at"`
}

func (q *Queries) InsertStatusHistory(ctx context.Context, arg InsertStatusHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertStatusHistory,
		arg.SevID,
		arg.FromStatus,
		arg.ToStatus,
		arg.UserID,
		arg.TransitionedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listStatusHistoryBySEVID = `-- name: ListStatusHistoryBySEVID :many
SELECT id, sev_id, from_status, to_status, user_id, transitioned_at
FROM sev_status_history
WHERE sev_id = $1
ORDER BY transitioned_at
`

func (q *Queries) ListStatusHistoryBySEVID(ctx context.Context, sevID string) ([]SevStatusHistory, error) {
	rows, err := q.db.Query(ctx, listStatusHistoryBySEVID, sevID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SevStatusHistory
	for rows.Next() {
		var i SevStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.SevID,
			&i.FromStatus,
			&i.ToStatus,
			&i.UserID,
			&i.TransitionedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
