// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLinkedTask = `-- name: DeleteLinkedTask :exec
DELETE FROM sev_linked_tasks WHERE id = $1
`

func (q *Queries) DeleteLinkedTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLinkedTask, id)
	return err
}

const getLinkedTask = `-- name: GetLinkedTask :one
SELECT id, sev_id, external_system, task_id, url, title, description,
       relationship_type, priority, due_date, overdue, created_at, created_by
FROM sev_linked_tasks
WHERE id = $1
`

func (q *Queries) GetLinkedTask(ctx context.Context, id int64) (SevLinkedTask, error) {
	row := q.db.QueryRow(ctx, getLinkedTask, id)
	var i SevLinkedTask
	err := row.Scan(
		&i.ID,
		&i.SevID,
		&i.ExternalSystem,
		&i.TaskID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.RelationshipType,
		&i.Priority,
		&i.DueDate,
		&i.Overdue,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertLinkedTask = `-- name: InsertLinkedTask :one
INSERT INTO sev_linked_tasks (
    sev_id, external_system, task_id, url, title, description,
    relationship_type, priority, due_date, overdue, created_at, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type InsertLinkedTaskParams struct {
	SevID            string             `json:"sev_id"`
	ExternalSystem   string             `json:"external_system"`
	TaskID           string             `json:"task_id"`
	Url              string             `json:"url"`
	Title            string             `json:"title"`
	Description      *string            `json:"description"`
	RelationshipType string             `json:"relationship_type"`
	Priority         string             `json:"priority"`
	DueDate          pgtype.Date        `json:"due_date"`
	Overdue          bool               `json:"overdue"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CreatedBy        string             `json:"created_by"`
}

func (q *Queries) InsertLinkedTask(ctx context.Context, arg InsertLinkedTaskParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertLinkedTask,
		arg.SevID,
		arg.ExternalSystem,
		arg.TaskID,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.RelationshipType,
		arg.Priority,
		arg.DueDate,
		arg.Overdue,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLinkedTasksBySEVID = `-- name: ListLinkedTasksBySEVID :many
SELECT id, sev_id, external_system, task_id, url, title, description,
       relationship_type, priority, due_date, overdue, created_at, created_by
FROM sev_linked_tasks
WHERE sev_id = $1
ORDER BY created_at
`

func (q *Queries) ListLinkedTasksBySEVID(ctx context.Context, sevID string) ([]SevLinkedTask, error) {
	rows, err := q.db.Query(ctx, listLinkedTasksBySEVID, sevID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SevLinkedTask
	for rows.Next() {
		var i SevLinkedTask
		if err := rows.Scan(
			&i.ID,
			&i.SevID,
			&i.ExternalSystem,
			&i.TaskID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.RelationshipType,
			&i.Priority,
			&i.DueDate,
			&i.Overdue,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLinkedTask = `-- name: UpdateLinkedTask :exec
UPDATE sev_linked_tasks SET
    title             = $2,
    description       = $3,
    relationship_type = $4,
    priority          = $5,
    due_date          = $6,
    overdue           = $7
WHERE id = $1
`

type UpdateLinkedTaskParams struct {
	ID               int64       `json:"id"`
	Title            string      `json:"title"`
	Description      *string     `json:"description"`
	RelationshipType string      `json:"relationship_type"`
	Priority         string      `json:"priority"`
	DueDate          pgtype.Date `json:"due_date"`
	Overdue          bool        `json:"overdue"`
}

func (q *Queries) UpdateLinkedTask(ctx context.Context, arg UpdateLinkedTaskParams) error {
	_, err := q.db.Exec(ctx, updateLinkedTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.RelationshipType,
		arg.Priority,
		arg.DueDate,
		arg.Overdue,
	)
	return err
}
