// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, email, name, avatar_url, org_role, active, oauth_provider, oauth_subject, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.OrgRole,
		&i.Active,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, avatar_url, org_role, active, oauth_provider, oauth_subject, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.OrgRole,
		&i.Active,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, email, name, avatar_url, org_role, active, oauth_provider, oauth_subject, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertUserParams struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	Name          string             `json:"name"`
	AvatarUrl     *string            `json:"avatar_url"`
	OrgRole       string             `json:"org_role"`
	Active        bool               `json:"active"`
	OauthProvider string             `json:"oauth_provider"`
	OauthSubject  string             `json:"oauth_subject"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.OrgRole,
		arg.Active,
		arg.OauthProvider,
		arg.OauthSubject,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, avatar_url, org_role, active, oauth_provider, oauth_subject, created_at, updated_at
FROM users
ORDER BY email
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.OrgRole,
			&i.Active,
			&i.OauthProvider,
			&i.OauthSubject,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    name       = $2,
    avatar_url = $3,
    org_role   = $4,
    active     = $5,
    updated_at = $6
WHERE id = $1
`

type UpdateUserParams struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	AvatarUrl *string            `json:"avatar_url"`
	OrgRole   string             `json:"org_role"`
	Active    bool               `json:"active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.AvatarUrl,
		arg.OrgRole,
		arg.Active,
		arg.UpdatedAt,
	)
	return err
}
